deploy: 07f5aa97c14ffbd2effc405971d21ce5d93c971a

diff --git a/target/docker/joint_embedding_metrics/calculate_rf_oob/calculate_rf_oob b/target/docker/joint_embedding_metrics/calculate_rf_oob/calculate_rf_oob
--- a/target/docker/joint_embedding_metrics/calculate_rf_oob/calculate_rf_oob
+++ b/target/docker/joint_embedding_metrics/calculate_rf_oob/calculate_rf_oob
@@ -144,21 +144,21 @@ function ViashHelp {
   echo
   echo "Options:"
 
-  echo "   -ip, --input_prediction"
-  echo "        type: file"
+  echo "   --input_prediction"
+  echo "        type: file, required parameter"
   echo "        example: prediction.h5ad"
-  echo "        Prediction by a method."
+  echo "        Prediction by a method"
   echo ""
 
 
-  echo "   -io, --input_solution"
+  echo "   --input_solution"
   echo "        type: file, required parameter"
   echo "        example: solution.h5ad"
   echo "        Gold standard solution."
   echo ""
 
 
-  echo "   -o, --output"
+  echo "   --output"
   echo "        type: file, required parameter, output"
   echo "        example: output.h5ad"
   echo "        Metric scores by comparing the prediction to the gold standard solution."
@@ -476,10 +476,6 @@ while [[ $# -gt 0 ]]; do
             VIASH_PAR_INPUT_PREDICTION=$(ViashRemoveFlags "$1")
             shift 1
             ;;
-        -ip)
-            VIASH_PAR_INPUT_PREDICTION="$2"
-            shift 2
-            ;;
         --input_solution)
             VIASH_PAR_INPUT_SOLUTION="$2"
             shift 2
@@ -488,10 +484,6 @@ while [[ $# -gt 0 ]]; do
             VIASH_PAR_INPUT_SOLUTION=$(ViashRemoveFlags "$1")
             shift 1
             ;;
-        -io)
-            VIASH_PAR_INPUT_SOLUTION="$2"
-            shift 2
-            ;;
         --output)
             VIASH_PAR_OUTPUT="$2"
             shift 2
@@ -499,10 +491,6 @@ while [[ $# -gt 0 ]]; do
         --output=*)
             VIASH_PAR_OUTPUT=$(ViashRemoveFlags "$1")
             shift 1
-            ;;
-        -o)
-            VIASH_PAR_OUTPUT="$2"
-            shift 2
             ;;
         ---setup)
             ViashDockerSetup 'openproblems/joint_embedding_metrics_calculate_rf_oob:main_build' "$2"
@@ -543,6 +531,10 @@ eval set -- $VIASH_POSITIONAL_ARGS
 
 
 # check whether required parameters exist
+if [ -z "$VIASH_PAR_INPUT_PREDICTION" ]; then
+  ViashError '--input_prediction' is a required argument. Use "--help" to get more information on the parameters.
+  exit 1
+fi
 if [ -z "$VIASH_PAR_INPUT_SOLUTION" ]; then
   ViashError '--input_solution' is a required argument. Use "--help" to get more information on the parameters.
   exit 1
diff --git a/target/docker/joint_embedding_metrics/calculate_rf_oob/viash.yaml b/target/docker/joint_embedding_metrics/calculate_rf_oob/viash.yaml
--- a/target/docker/joint_embedding_metrics/calculate_rf_oob/viash.yaml
+++ b/target/docker/joint_embedding_metrics/calculate_rf_oob/viash.yaml
@@ -14,19 +14,17 @@ functionality:
   arguments:
   - type: "file"
     name: "--input_prediction"
-    alternatives:
-    - "-ip"
-    description: "Prediction by a method."
+    alternatives: []
+    description: "Prediction by a method"
     example: "prediction.h5ad"
     must_exist: false
-    required: false
+    required: true
     direction: "Input"
     multiple: false
     multiple_sep: ":"
   - type: "file"
     name: "--input_solution"
-    alternatives:
-    - "-io"
+    alternatives: []
     description: "Gold standard solution."
     example: "solution.h5ad"
     must_exist: false
@@ -36,8 +34,7 @@ functionality:
     multiple_sep: ":"
   - type: "file"
     name: "--output"
-    alternatives:
-    - "-o"
+    alternatives: []
     description: "Metric scores by comparing the prediction to the gold standard solution."
     example: "output.h5ad"
     must_exist: false
@@ -194,21 +191,21 @@ functionality:
         echo
         echo "Options:"
       
-        echo "   -ip, --input_prediction"
-        echo "        type: file"
+        echo "   --input_prediction"
+        echo "        type: file, required parameter"
         echo "        example: prediction.h5ad"
-        echo "        Prediction by a method."
+        echo "        Prediction by a method"
         echo ""
       
       
-        echo "   -io, --input_solution"
+        echo "   --input_solution"
         echo "        type: file, required parameter"
         echo "        example: solution.h5ad"
         echo "        Gold standard solution."
         echo ""
       
       
-        echo "   -o, --output"
+        echo "   --output"
         echo "        type: file, required parameter, output"
         echo "        example: output.h5ad"
         echo "        Metric scores by comparing the prediction to the gold standard solution."
@@ -526,10 +523,6 @@ functionality:
                   VIASH_PAR_INPUT_PREDICTION=$(ViashRemoveFlags "$1")
                   shift 1
                   ;;
-              -ip)
-                  VIASH_PAR_INPUT_PREDICTION="$2"
-                  shift 2
-                  ;;
               --input_solution)
                   VIASH_PAR_INPUT_SOLUTION="$2"
                   shift 2
@@ -538,10 +531,6 @@ functionality:
                   VIASH_PAR_INPUT_SOLUTION=$(ViashRemoveFlags "$1")
                   shift 1
                   ;;
-              -io)
-                  VIASH_PAR_INPUT_SOLUTION="$2"
-                  shift 2
-                  ;;
               --output)
                   VIASH_PAR_OUTPUT="$2"
                   shift 2
@@ -549,10 +538,6 @@ functionality:
               --output=*)
                   VIASH_PAR_OUTPUT=$(ViashRemoveFlags "$1")
                   shift 1
-                  ;;
-              -o)
-                  VIASH_PAR_OUTPUT="$2"
-                  shift 2
                   ;;
               ---setup)
                   ViashDockerSetup 'openproblems/joint_embedding_metrics_calculate_rf_oob:main_build' "$2"
@@ -593,6 +578,10 @@ functionality:
       
       
       # check whether required parameters exist
+      if [ -z "$VIASH_PAR_INPUT_PREDICTION" ]; then
+        ViashError '--input_prediction' is a required argument. Use "--help" to get more information on the parameters.
+        exit 1
+      fi
       if [ -z "$VIASH_PAR_INPUT_SOLUTION" ]; then
         ViashError '--input_solution' is a required argument. Use "--help" to get more information on the parameters.
         exit 1
@@ -752,5 +741,5 @@ info:
   output: "target/docker/joint_embedding_metrics/calculate_rf_oob"
   executable: "target/docker/joint_embedding_metrics/calculate_rf_oob/calculate_rf_oob"
   viash_version: "0.5.1"
-  git_commit: "bcb039584d51d9f899f85d95fceb762e7efff254"
+  git_commit: "07f5aa97c14ffbd2effc405971d21ce5d93c971a"
   git_remote: "https://github.com/openproblems-bio/neurips2021_multimodal_viash"
diff --git a/target/nextflow/joint_embedding_metrics/calculate_rf_oob/viash.yaml b/target/nextflow/joint_embedding_metrics/calculate_rf_oob/viash.yaml
--- a/target/nextflow/joint_embedding_metrics/calculate_rf_oob/viash.yaml
+++ b/target/nextflow/joint_embedding_metrics/calculate_rf_oob/viash.yaml
@@ -14,19 +14,17 @@ functionality:
   arguments:
   - type: "file"
     name: "--input_prediction"
-    alternatives:
-    - "-ip"
-    description: "Prediction by a method."
+    alternatives: []
+    description: "Prediction by a method"
     example: "prediction.h5ad"
     must_exist: false
-    required: false
+    required: true
     direction: "Input"
     multiple: false
     multiple_sep: ":"
   - type: "file"
     name: "--input_solution"
-    alternatives:
-    - "-io"
+    alternatives: []
     description: "Gold standard solution."
     example: "solution.h5ad"
     must_exist: false
@@ -36,8 +34,7 @@ functionality:
     multiple_sep: ":"
   - type: "file"
     name: "--output"
-    alternatives:
-    - "-o"
+    alternatives: []
     description: "Metric scores by comparing the prediction to the gold standard solution."
     example: "output.h5ad"
     must_exist: false
@@ -194,21 +191,21 @@ functionality:
         echo
         echo "Options:"
       
-        echo "   -ip, --input_prediction"
-        echo "        type: file"
+        echo "   --input_prediction"
+        echo "        type: file, required parameter"
         echo "        example: prediction.h5ad"
-        echo "        Prediction by a method."
+        echo "        Prediction by a method"
         echo ""
       
       
-        echo "   -io, --input_solution"
+        echo "   --input_solution"
         echo "        type: file, required parameter"
         echo "        example: solution.h5ad"
         echo "        Gold standard solution."
         echo ""
       
       
-        echo "   -o, --output"
+        echo "   --output"
         echo "        type: file, required parameter, output"
         echo "        example: output.h5ad"
         echo "        Metric scores by comparing the prediction to the gold standard solution."
@@ -253,10 +250,6 @@ functionality:
                   VIASH_PAR_INPUT_PREDICTION=$(ViashRemoveFlags "$1")
                   shift 1
                   ;;
-              -ip)
-                  VIASH_PAR_INPUT_PREDICTION="$2"
-                  shift 2
-                  ;;
               --input_solution)
                   VIASH_PAR_INPUT_SOLUTION="$2"
                   shift 2
@@ -265,10 +258,6 @@ functionality:
                   VIASH_PAR_INPUT_SOLUTION=$(ViashRemoveFlags "$1")
                   shift 1
                   ;;
-              -io)
-                  VIASH_PAR_INPUT_SOLUTION="$2"
-                  shift 2
-                  ;;
               --output)
                   VIASH_PAR_OUTPUT="$2"
                   shift 2
@@ -276,10 +265,6 @@ functionality:
               --output=*)
                   VIASH_PAR_OUTPUT=$(ViashRemoveFlags "$1")
                   shift 1
-                  ;;
-              -o)
-                  VIASH_PAR_OUTPUT="$2"
-                  shift 2
                   ;;
               *)  # positional arg or unknown option
                   # since the positional args will be eval'd, can we always quote, instead of using ViashQuote
@@ -295,6 +280,10 @@ functionality:
       
       
       # check whether required parameters exist
+      if [ -z "$VIASH_PAR_INPUT_PREDICTION" ]; then
+        ViashError '--input_prediction' is a required argument. Use "--help" to get more information on the parameters.
+        exit 1
+      fi
       if [ -z "$VIASH_PAR_INPUT_SOLUTION" ]; then
         ViashError '--input_solution' is a required argument. Use "--help" to get more information on the parameters.
         exit 1
@@ -387,7 +376,7 @@ functionality:
         docker.runOptions = "-i -v ${baseDir}:${baseDir}"
         process.container = "dataintuitive/viash"
         params {
-          calculate_rf_oob__input_prediction = "no_default_value_configured"
+          calculate_rf_oob__input_prediction = "viash_no_value"
           calculate_rf_oob__input_solution = "viash_no_value"
           calculate_rf_oob__output = "viash_no_value"
           id = ""
@@ -408,14 +397,14 @@ functionality:
               input_prediction {
                 name = "input_prediction"
                 otype = "--"
-                required = false
+                required = true
                 type = "file"
                 direction = "Input"
                 multiple = false
                 multiple_sep = ":"
                 value = "${params.calculate_rf_oob__input_prediction}"
                 example = "prediction.h5ad"
-                description = "Prediction by a method."
+                description = "Prediction by a method"
               }
               input_solution {
                 name = "input_solution"
@@ -798,5 +787,5 @@ info:
   output: "target/nextflow/joint_embedding_metrics/calculate_rf_oob"
   executable: "target/nextflow/joint_embedding_metrics/calculate_rf_oob/calculate_rf_oob"
   viash_version: "0.5.1"
-  git_commit: "bcb039584d51d9f899f85d95fceb762e7efff254"
+  git_commit: "07f5aa97c14ffbd2effc405971d21ce5d93c971a"
   git_remote: "https://github.com/openproblems-bio/neurips2021_multimodal_viash"
