deploy: 9bf7a41e61442bc9df05735575ddf66f20776cd4

diff --git a/target/nextflow/predict_modality_datasets/censor_dataset/censor_dataset b/target/nextflow/predict_modality_datasets/censor_dataset/censor_dataset
--- a/target/nextflow/predict_modality_datasets/censor_dataset/censor_dataset
+++ b/target/nextflow/predict_modality_datasets/censor_dataset/censor_dataset
@@ -159,21 +159,28 @@ function ViashHelp {
   echo ""
 
 
-  echo "   --output_mod1"
+  echo "   --output_train_mod1"
   echo "        type: file, required parameter, output"
-  echo "        example: dataset_mod1.h5ad"
-  echo "        Mod1 h5ad file for both train and test cells."
+  echo "        example: dataset_train_mod1.h5ad"
+  echo "        Mod1 h5ad file for only the train cells."
   echo ""
 
 
-  echo "   --output_mod2"
+  echo "   --output_train_mod2"
   echo "        type: file, required parameter, output"
   echo "        example: dataset_mod2.h5ad"
   echo "        Mod2 h5ad file for only the train cells."
   echo ""
 
 
-  echo "   --output_solution"
+  echo "   --output_test_mod1"
+  echo "        type: file, required parameter, output"
+  echo "        example: dataset_test_mod1.h5ad"
+  echo "        Mod1 h5ad file for only the test cells."
+  echo ""
+
+
+  echo "   --output_test_mod2"
   echo "        type: file, required parameter, output"
   echo "        example: dataset_solution.h5ad"
   echo "        Mod2 h5ad file for only the test cells."
@@ -244,28 +251,36 @@ while [[ $# -gt 0 ]]; do
             VIASH_PAR_INPUT_MOD2=$(ViashRemoveFlags "$1")
             shift 1
             ;;
-        --output_mod1)
-            VIASH_PAR_OUTPUT_MOD1="$2"
+        --output_train_mod1)
+            VIASH_PAR_OUTPUT_TRAIN_MOD1="$2"
             shift 2
             ;;
-        --output_mod1=*)
-            VIASH_PAR_OUTPUT_MOD1=$(ViashRemoveFlags "$1")
+        --output_train_mod1=*)
+            VIASH_PAR_OUTPUT_TRAIN_MOD1=$(ViashRemoveFlags "$1")
             shift 1
             ;;
-        --output_mod2)
-            VIASH_PAR_OUTPUT_MOD2="$2"
+        --output_train_mod2)
+            VIASH_PAR_OUTPUT_TRAIN_MOD2="$2"
             shift 2
             ;;
-        --output_mod2=*)
-            VIASH_PAR_OUTPUT_MOD2=$(ViashRemoveFlags "$1")
+        --output_train_mod2=*)
+            VIASH_PAR_OUTPUT_TRAIN_MOD2=$(ViashRemoveFlags "$1")
             shift 1
             ;;
-        --output_solution)
-            VIASH_PAR_OUTPUT_SOLUTION="$2"
+        --output_test_mod1)
+            VIASH_PAR_OUTPUT_TEST_MOD1="$2"
             shift 2
             ;;
-        --output_solution=*)
-            VIASH_PAR_OUTPUT_SOLUTION=$(ViashRemoveFlags "$1")
+        --output_test_mod1=*)
+            VIASH_PAR_OUTPUT_TEST_MOD1=$(ViashRemoveFlags "$1")
+            shift 1
+            ;;
+        --output_test_mod2)
+            VIASH_PAR_OUTPUT_TEST_MOD2="$2"
+            shift 2
+            ;;
+        --output_test_mod2=*)
+            VIASH_PAR_OUTPUT_TEST_MOD2=$(ViashRemoveFlags "$1")
             shift 1
             ;;
         --seed)
@@ -314,16 +329,20 @@ if [ -z "$VIASH_PAR_INPUT_MOD2" ]; then
   ViashError '--input_mod2' is a required argument. Use "--help" to get more information on the parameters.
   exit 1
 fi
-if [ -z "$VIASH_PAR_OUTPUT_MOD1" ]; then
-  ViashError '--output_mod1' is a required argument. Use "--help" to get more information on the parameters.
+if [ -z "$VIASH_PAR_OUTPUT_TRAIN_MOD1" ]; then
+  ViashError '--output_train_mod1' is a required argument. Use "--help" to get more information on the parameters.
   exit 1
 fi
-if [ -z "$VIASH_PAR_OUTPUT_MOD2" ]; then
-  ViashError '--output_mod2' is a required argument. Use "--help" to get more information on the parameters.
+if [ -z "$VIASH_PAR_OUTPUT_TRAIN_MOD2" ]; then
+  ViashError '--output_train_mod2' is a required argument. Use "--help" to get more information on the parameters.
   exit 1
 fi
-if [ -z "$VIASH_PAR_OUTPUT_SOLUTION" ]; then
-  ViashError '--output_solution' is a required argument. Use "--help" to get more information on the parameters.
+if [ -z "$VIASH_PAR_OUTPUT_TEST_MOD1" ]; then
+  ViashError '--output_test_mod1' is a required argument. Use "--help" to get more information on the parameters.
+  exit 1
+fi
+if [ -z "$VIASH_PAR_OUTPUT_TEST_MOD2" ]; then
+  ViashError '--output_test_mod2' is a required argument. Use "--help" to get more information on the parameters.
   exit 1
 fi
 
@@ -349,9 +368,10 @@ library(Matrix, quietly = TRUE, warn.conflicts = FALSE)
 par <- list(
   "input_mod1" = $( if [ ! -z ${VIASH_PAR_INPUT_MOD1+x} ]; then echo "'$VIASH_PAR_INPUT_MOD1'"; else echo NULL; fi ),
   "input_mod2" = $( if [ ! -z ${VIASH_PAR_INPUT_MOD2+x} ]; then echo "'$VIASH_PAR_INPUT_MOD2'"; else echo NULL; fi ),
-  "output_mod1" = $( if [ ! -z ${VIASH_PAR_OUTPUT_MOD1+x} ]; then echo "'$VIASH_PAR_OUTPUT_MOD1'"; else echo NULL; fi ),
-  "output_mod2" = $( if [ ! -z ${VIASH_PAR_OUTPUT_MOD2+x} ]; then echo "'$VIASH_PAR_OUTPUT_MOD2'"; else echo NULL; fi ),
-  "output_solution" = $( if [ ! -z ${VIASH_PAR_OUTPUT_SOLUTION+x} ]; then echo "'$VIASH_PAR_OUTPUT_SOLUTION'"; else echo NULL; fi ),
+  "output_train_mod1" = $( if [ ! -z ${VIASH_PAR_OUTPUT_TRAIN_MOD1+x} ]; then echo "'$VIASH_PAR_OUTPUT_TRAIN_MOD1'"; else echo NULL; fi ),
+  "output_train_mod2" = $( if [ ! -z ${VIASH_PAR_OUTPUT_TRAIN_MOD2+x} ]; then echo "'$VIASH_PAR_OUTPUT_TRAIN_MOD2'"; else echo NULL; fi ),
+  "output_test_mod1" = $( if [ ! -z ${VIASH_PAR_OUTPUT_TEST_MOD1+x} ]; then echo "'$VIASH_PAR_OUTPUT_TEST_MOD1'"; else echo NULL; fi ),
+  "output_test_mod2" = $( if [ ! -z ${VIASH_PAR_OUTPUT_TEST_MOD2+x} ]; then echo "'$VIASH_PAR_OUTPUT_TEST_MOD2'"; else echo NULL; fi ),
   "seed" = $( if [ ! -z ${VIASH_PAR_SEED+x} ]; then echo "as.integer($VIASH_PAR_SEED)"; else echo NULL; fi ),
   "max_mod1_columns" = $( if [ ! -z ${VIASH_PAR_MAX_MOD1_COLUMNS+x} ]; then echo "as.integer($VIASH_PAR_MAX_MOD1_COLUMNS)"; else echo NULL; fi ),
   "max_mod2_columns" = $( if [ ! -z ${VIASH_PAR_MAX_MOD2_COLUMNS+x} ]; then echo "as.integer($VIASH_PAR_MAX_MOD2_COLUMNS)"; else echo NULL; fi )
@@ -369,93 +389,50 @@ ad2_mod <- unique(ad2_raw\$var[["feature_types"]])
 new_dataset_id <- paste0(ad1_raw\$uns[["dataset_id"]], "_PM_", tolower(ad1_mod), "2", tolower(ad2_mod))
 common_uns <- list(dataset_id = new_dataset_id)
 
-cat("Determining train/test group\\n")
-group <-
-  if (!is.null(ad1_raw\$obs[["batch"]]) && all(ad1_raw\$obs[["batch"]] %in% c("train", "test"))) {
-    ad1_raw\$obs[["batch"]]
-  } else if (!is.null(ad1_raw\$obs[["batch"]])) {
-    # use batch label to optimise the best train/test split
-    batch <- as.character(ad1_raw\$obs[["batch"]])
-    nums <- table(batch)
-    nums <- setNames(as.numeric(nums), names(nums))
-
-    # try to find a split that best matches 0.66
-    ga_out <- GA::ga(
-      type = "binary",
-      nBits = length(nums),
-      fitness = function(x) {
-        -abs(sum(nums[x == 1]) / sum(nums) - 0.66)
-      },
-      maxiter = 500,
-      monitor = FALSE
-    )
-    train_batches <- names(nums)[ga_out@solution[1,] == 1]
-    ifelse(batch %in% train_batches, "train", "test")
-  } else {
-    # split randomly
-    set.seed(par\$seed)
-    ix <- sample.int(
-      nrow(ad1_raw), 
-      size = nrow(ad1_raw) * 0.66,
-      replace = FALSE
-    )
-    ifelse(seq_len(nrow(ad1_raw)) %in% ix, "train", "test")
-  }
-splor <- order(group)
-ad1_X <- ad1_raw\$X[splor,, drop = FALSE]
-ad2_X <- ad2_raw\$X[splor,, drop = FALSE]
-group <- group[splor]
-
-if (!is.null(par\$max_mod1_columns) && par\$max_mod1_columns < ncol(ad1_X)) {
+if (!is.null(par\$max_mod1_columns) && par\$max_mod1_columns < ncol(ad1_raw)) {
   cat("Sampling mod1 columns\\n")
-  ad1_ix <- sample.int(ncol(ad1_X), par\$max_mod1_columns)
-  ad1_X <- ad1_X[, ad1_ix, drop = FALSE]
+  ad1_ix <- sample.int(ncol(ad1_raw), par\$max_mod1_columns)
+  ad1_raw <- ad1_raw[, ad1_ix, drop = FALSE]
 }
-if (!is.null(par\$max_mod2_columns) && par\$max_mod2_columns < ncol(ad2_X)) {
+if (!is.null(par\$max_mod2_columns) && par\$max_mod2_columns < ncol(ad2_raw)) {
   cat("Sampling mod2 columns\\n")
-  ad2_ix <- sample.int(ncol(ad2_X), par\$max_mod2_columns)
-  ad2_X <- ad2_X[, ad2_ix, drop = FALSE]
+  ad2_ix <- sample.int(ncol(ad2_raw), par\$max_mod2_columns)
+  ad2_raw <- ad2_raw[, ad2_ix, drop = FALSE]
 }
 
-cat("Creating mod1 object\\n")
-out_mod1 <- anndata::AnnData(
-  X = ad1_X,
-  var = ad1_raw\$var %>% select(one_of("gene_ids"), feature_types),
-  obs = ad1_raw\$obs[splor, ] %>% select(one_of("batch")) %>% mutate(group),
-  uns = common_uns
-)
-
-cat("Creating mod2 object\\n")
+cat("Creating train objects\\n")
+ad1_var <- ad1_raw\$var %>% select(one_of("gene_ids"), feature_types)
 ad2_var <- ad2_raw\$var %>% select(one_of("gene_ids"), feature_types)
-ad2_obs <- ad2_raw\$obs[splor, ] %>% select(one_of("batch")) %>% mutate(group)
+is_train <- ad1_raw\$obs[["is_train"]]
 
-out_mod2 <- anndata::AnnData(
-  X = ad2_X[group == "train", , drop = FALSE],
+out_train_mod1 <- anndata::AnnData(
+  X = ad1_raw\$X[is_train, , drop = FALSE],
+  var = ad1_var,
+  uns = common_uns
+)
+out_train_mod2 <- anndata::AnnData(
+  X = ad2_raw\$X[is_train, , drop = FALSE],
   var = ad2_var,
-  obs = ad2_obs[group == "train", , drop = FALSE],
   uns = common_uns
 )
 
-cat("Create solution object\\n")
-out_solution <- anndata::AnnData(
-  X = ad2_X[group == "test", , drop = FALSE],
+cat("Create test objects\\n")
+out_test_mod1 <- anndata::AnnData(
+  X = ad1_raw\$X[!is_train, , drop = FALSE],
+  var = ad1_var,
+  uns = common_uns
+)
+out_test_mod2 <- anndata::AnnData(
+  X = ad2_raw\$X[!is_train, , drop = FALSE],
   var = ad2_var,
-  obs = ad2_obs[group == "test", , drop = FALSE],
   uns = common_uns
 )
 
 cat("Saving output files as h5ad\\n")
-cat("output_mod1:")
-print(out_mod1)
-zzz <- out_mod1\$write_h5ad(par\$output_mod1, compression = "gzip")
-
-cat("output_mod2:")
-print(out_mod2)
-zzz <- out_mod2\$write_h5ad(par\$output_mod2, compression = "gzip")
-
-cat("output_solution:")
-print(out_solution)
-zzz <- out_solution\$write_h5ad(par\$output_solution, compression = "gzip")
+zzz <- out_train_mod1\$write_h5ad(par\$output_train_mod1, compression = "gzip")
+zzz <- out_train_mod2\$write_h5ad(par\$output_train_mod2, compression = "gzip")
+zzz <- out_test_mod1\$write_h5ad(par\$output_test_mod1, compression = "gzip")
+zzz <- out_test_mod2\$write_h5ad(par\$output_test_mod2, compression = "gzip")
 VIASHMAIN
 PATH="$VIASH_RESOURCES_DIR:\$PATH"
 
