deploy: 4c6e1e835fe2936616c5aa0aacb7a77b775a4e09

diff --git a/target/docker/common_datasets/download_10x_dataset/download_10x_dataset b/target/docker/common_datasets/download_10x_dataset/download_10x_dataset
--- a/target/docker/common_datasets/download_10x_dataset/download_10x_dataset
+++ b/target/docker/common_datasets/download_10x_dataset/download_10x_dataset
@@ -163,6 +163,13 @@ function ViashHelp {
   echo ""
 
 
+  echo "   --organism"
+  echo "        type: string, required parameter"
+  echo "        example: human"
+  echo "        The organism of the dataset"
+  echo ""
+
+
   echo "   --output_rna"
   echo "        type: file, required parameter, output"
   echo "        example: output_rna.h5ad"
@@ -499,6 +506,14 @@ while [[ $# -gt 0 ]]; do
             VIASH_PAR_INPUT=$(ViashRemoveFlags "$1")
             shift 1
             ;;
+        --organism)
+            VIASH_PAR_ORGANISM="$2"
+            shift 2
+            ;;
+        --organism=*)
+            VIASH_PAR_ORGANISM=$(ViashRemoveFlags "$1")
+            shift 1
+            ;;
         --output_rna)
             VIASH_PAR_OUTPUT_RNA="$2"
             shift 2
@@ -560,6 +575,10 @@ if [ -z "$VIASH_PAR_ID" ]; then
 fi
 if [ -z "$VIASH_PAR_INPUT" ]; then
   ViashError '--input' is a required argument. Use "--help" to get more information on the parameters.
+  exit 1
+fi
+if [ -z "$VIASH_PAR_ORGANISM" ]; then
+  ViashError '--organism' is a required argument. Use "--help" to get more information on the parameters.
   exit 1
 fi
 if [ -z "$VIASH_PAR_OUTPUT_RNA" ]; then
@@ -624,6 +643,7 @@ sc <- reticulate::import("scanpy")
 par <- list(
   "id" = $( if [ ! -z ${VIASH_PAR_ID+x} ]; then echo "'$VIASH_PAR_ID'"; else echo NULL; fi ),
   "input" = $( if [ ! -z ${VIASH_PAR_INPUT+x} ]; then echo "'$VIASH_PAR_INPUT'"; else echo NULL; fi ),
+  "organism" = $( if [ ! -z ${VIASH_PAR_ORGANISM+x} ]; then echo "'$VIASH_PAR_ORGANISM'"; else echo NULL; fi ),
   "output_rna" = $( if [ ! -z ${VIASH_PAR_OUTPUT_RNA+x} ]; then echo "'$VIASH_PAR_OUTPUT_RNA'"; else echo NULL; fi ),
   "output_mod2" = $( if [ ! -z ${VIASH_PAR_OUTPUT_MOD2+x} ]; then echo "'$VIASH_PAR_OUTPUT_MOD2'"; else echo NULL; fi )
 )
@@ -642,6 +662,7 @@ ad <- sc\$read_10x_h5(h5_tmp, gex_only = FALSE)
 
 cat("Setting dataset id\\n")
 ad\$uns[["dataset_id"]] <- par\$id
+ad\$uns[["organism"]] <- par\$organism
 
 cat("Making var names unique\\n")
 zzz <- ad\$var_names_make_unique()
diff --git a/target/nextflow/common_datasets/download_10x_dataset/viash.yaml b/target/nextflow/common_datasets/download_10x_dataset/viash.yaml
--- a/target/nextflow/common_datasets/download_10x_dataset/viash.yaml
+++ b/target/nextflow/common_datasets/download_10x_dataset/viash.yaml
@@ -29,6 +29,15 @@ functionality:
     direction: "Input"
     multiple: false
     multiple_sep: ":"
+  - type: "string"
+    name: "--organism"
+    alternatives: []
+    description: "The organism of the dataset"
+    example: "human"
+    required: true
+    direction: "Input"
+    multiple: false
+    multiple_sep: ":"
   - type: "file"
     name: "--output_rna"
     alternatives: []
@@ -217,6 +226,13 @@ functionality:
         echo ""
       
       
+        echo "   --organism"
+        echo "        type: string, required parameter"
+        echo "        example: human"
+        echo "        The organism of the dataset"
+        echo ""
+      
+      
         echo "   --output_rna"
         echo "        type: file, required parameter, output"
         echo "        example: output_rna.h5ad"
@@ -277,6 +293,14 @@ functionality:
                   VIASH_PAR_INPUT=$(ViashRemoveFlags "$1")
                   shift 1
                   ;;
+              --organism)
+                  VIASH_PAR_ORGANISM="$2"
+                  shift 2
+                  ;;
+              --organism=*)
+                  VIASH_PAR_ORGANISM=$(ViashRemoveFlags "$1")
+                  shift 1
+                  ;;
               --output_rna)
                   VIASH_PAR_OUTPUT_RNA="$2"
                   shift 2
@@ -315,6 +339,10 @@ functionality:
         ViashError '--input' is a required argument. Use "--help" to get more information on the parameters.
         exit 1
       fi
+      if [ -z "$VIASH_PAR_ORGANISM" ]; then
+        ViashError '--organism' is a required argument. Use "--help" to get more information on the parameters.
+        exit 1
+      fi
       if [ -z "$VIASH_PAR_OUTPUT_RNA" ]; then
         ViashError '--output_rna' is a required argument. Use "--help" to get more information on the parameters.
         exit 1
@@ -345,6 +373,7 @@ functionality:
       par <- list(
         "id" = $( if [ ! -z ${VIASH_PAR_ID+x} ]; then echo "'$VIASH_PAR_ID'"; else echo NULL; fi ),
         "input" = $( if [ ! -z ${VIASH_PAR_INPUT+x} ]; then echo "'$VIASH_PAR_INPUT'"; else echo NULL; fi ),
+        "organism" = $( if [ ! -z ${VIASH_PAR_ORGANISM+x} ]; then echo "'$VIASH_PAR_ORGANISM'"; else echo NULL; fi ),
         "output_rna" = $( if [ ! -z ${VIASH_PAR_OUTPUT_RNA+x} ]; then echo "'$VIASH_PAR_OUTPUT_RNA'"; else echo NULL; fi ),
         "output_mod2" = $( if [ ! -z ${VIASH_PAR_OUTPUT_MOD2+x} ]; then echo "'$VIASH_PAR_OUTPUT_MOD2'"; else echo NULL; fi )
       )
@@ -363,6 +392,7 @@ functionality:
       
       cat("Setting dataset id\\n")
       ad\$uns[["dataset_id"]] <- par\$id
+      ad\$uns[["organism"]] <- par\$organism
       
       cat("Making var names unique\\n")
       zzz <- ad\$var_names_make_unique()
@@ -418,6 +448,7 @@ functionality:
         params {
           download_10x_dataset__id = "viash_no_value"
           download_10x_dataset__input = "viash_no_value"
+          download_10x_dataset__organism = "viash_no_value"
           download_10x_dataset__output_rna = "viash_no_value"
           download_10x_dataset__output_mod2 = "viash_no_value"
           id = ""
@@ -458,6 +489,18 @@ functionality:
                 value = "${params.download_10x_dataset__input}"
                 example = "https://cf.10xgenomics.com/samples/cell-exp/3.0.0/pbmc_1k_protein_v3/pbmc_1k_protein_v3_raw_feature_bc_matrix.h5"
                 description = "Location URL to an h5 file from the 10x genomics website."
+              }
+              organism {
+                name = "organism"
+                otype = "--"
+                required = true
+                type = "string"
+                direction = "Input"
+                multiple = false
+                multiple_sep = ":"
+                value = "${params.download_10x_dataset__organism}"
+                example = "human"
+                description = "The organism of the dataset"
               }
               output_rna {
                 name = "output_rna"
@@ -864,5 +907,5 @@ info:
   output: "target/nextflow/common_datasets/download_10x_dataset"
   executable: "target/nextflow/common_datasets/download_10x_dataset/download_10x_dataset"
   viash_version: "0.5.1"
-  git_commit: "b221ccab2261e73ff24f9b228ed6aabf28d96a0a"
+  git_commit: "4c6e1e835fe2936616c5aa0aacb7a77b775a4e09"
   git_remote: "https://github.com/openproblems-bio/neurips2021_multimodal_viash"
