deploy: 6f575b2a9df44c62b311887a52b1f9c16a9f6a1c

diff --git a/target/docker/match_modality_datasets/censor_dataset/viash.yaml b/target/docker/match_modality_datasets/censor_dataset/viash.yaml
--- a/target/docker/match_modality_datasets/censor_dataset/viash.yaml
+++ b/target/docker/match_modality_datasets/censor_dataset/viash.yaml
@@ -33,9 +33,9 @@ functionality:
     multiple: false
     multiple_sep: ":"
   - type: "file"
-    name: "--output_mod1"
+    name: "--output_train_mod1"
     alternatives: []
-    description: "A censored version of the first modality of the dataset."
+    description: "The censored shuffled train mod1 profiles."
     example: "dataset_censored.h5ad"
     must_exist: false
     required: true
@@ -43,9 +43,9 @@ functionality:
     multiple: false
     multiple_sep: ":"
   - type: "file"
-    name: "--output_mod2"
+    name: "--output_train_mod2"
     alternatives: []
-    description: "A censored version of the second modality of the dataset."
+    description: "The censored shuffled train mod2 profiles."
     example: "dataset_censored.h5ad"
     must_exist: false
     required: true
@@ -53,9 +53,39 @@ functionality:
     multiple: false
     multiple_sep: ":"
   - type: "file"
-    name: "--output_solution"
+    name: "--output_train_sol"
     alternatives: []
-    description: "A solution of the dataset"
+    description: "The pairing of train mod1&mod2 profiles."
+    example: "dataset_solution.h5ad"
+    must_exist: false
+    required: true
+    direction: "Output"
+    multiple: false
+    multiple_sep: ":"
+  - type: "file"
+    name: "--output_test_mod1"
+    alternatives: []
+    description: "The censored shuffled test mod1 profiles."
+    example: "dataset_censored.h5ad"
+    must_exist: false
+    required: true
+    direction: "Output"
+    multiple: false
+    multiple_sep: ":"
+  - type: "file"
+    name: "--output_test_mod2"
+    alternatives: []
+    description: "The censored shuffled test mod2 profiles."
+    example: "dataset_censored.h5ad"
+    must_exist: false
+    required: true
+    direction: "Output"
+    multiple: false
+    multiple_sep: ":"
+  - type: "file"
+    name: "--output_test_sol"
+    alternatives: []
+    description: "The pairing of test mod1&mod2 profiles."
     example: "dataset_solution.h5ad"
     must_exist: false
     required: true
@@ -226,24 +256,45 @@ functionality:
         echo ""
       
       
-        echo "   --output_mod1"
+        echo "   --output_train_mod1"
         echo "        type: file, required parameter, output"
         echo "        example: dataset_censored.h5ad"
-        echo "        A censored version of the first modality of the dataset."
+        echo "        The censored shuffled train mod1 profiles."
         echo ""
       
       
-        echo "   --output_mod2"
+        echo "   --output_train_mod2"
         echo "        type: file, required parameter, output"
         echo "        example: dataset_censored.h5ad"
-        echo "        A censored version of the second modality of the dataset."
+        echo "        The censored shuffled train mod2 profiles."
         echo ""
       
       
-        echo "   --output_solution"
+        echo "   --output_train_sol"
         echo "        type: file, required parameter, output"
         echo "        example: dataset_solution.h5ad"
-        echo "        A solution of the dataset"
+        echo "        The pairing of train mod1&mod2 profiles."
+        echo ""
+      
+      
+        echo "   --output_test_mod1"
+        echo "        type: file, required parameter, output"
+        echo "        example: dataset_censored.h5ad"
+        echo "        The censored shuffled test mod1 profiles."
+        echo ""
+      
+      
+        echo "   --output_test_mod2"
+        echo "        type: file, required parameter, output"
+        echo "        example: dataset_censored.h5ad"
+        echo "        The censored shuffled test mod2 profiles."
+        echo ""
+      
+      
+        echo "   --output_test_sol"
+        echo "        type: file, required parameter, output"
+        echo "        example: dataset_solution.h5ad"
+        echo "        The pairing of test mod1&mod2 profiles."
         echo ""
       
       }
@@ -566,28 +617,52 @@ functionality:
                   VIASH_PAR_INPUT_MOD2=$(ViashRemoveFlags "$1")
                   shift 1
                   ;;
-              --output_mod1)
-                  VIASH_PAR_OUTPUT_MOD1="$2"
+              --output_train_mod1)
+                  VIASH_PAR_OUTPUT_TRAIN_MOD1="$2"
                   shift 2
                   ;;
-              --output_mod1=*)
-                  VIASH_PAR_OUTPUT_MOD1=$(ViashRemoveFlags "$1")
+              --output_train_mod1=*)
+                  VIASH_PAR_OUTPUT_TRAIN_MOD1=$(ViashRemoveFlags "$1")
                   shift 1
                   ;;
-              --output_mod2)
-                  VIASH_PAR_OUTPUT_MOD2="$2"
+              --output_train_mod2)
+                  VIASH_PAR_OUTPUT_TRAIN_MOD2="$2"
                   shift 2
                   ;;
-              --output_mod2=*)
-                  VIASH_PAR_OUTPUT_MOD2=$(ViashRemoveFlags "$1")
+              --output_train_mod2=*)
+                  VIASH_PAR_OUTPUT_TRAIN_MOD2=$(ViashRemoveFlags "$1")
                   shift 1
                   ;;
-              --output_solution)
-                  VIASH_PAR_OUTPUT_SOLUTION="$2"
+              --output_train_sol)
+                  VIASH_PAR_OUTPUT_TRAIN_SOL="$2"
                   shift 2
                   ;;
-              --output_solution=*)
-                  VIASH_PAR_OUTPUT_SOLUTION=$(ViashRemoveFlags "$1")
+              --output_train_sol=*)
+                  VIASH_PAR_OUTPUT_TRAIN_SOL=$(ViashRemoveFlags "$1")
+                  shift 1
+                  ;;
+              --output_test_mod1)
+                  VIASH_PAR_OUTPUT_TEST_MOD1="$2"
+                  shift 2
+                  ;;
+              --output_test_mod1=*)
+                  VIASH_PAR_OUTPUT_TEST_MOD1=$(ViashRemoveFlags "$1")
+                  shift 1
+                  ;;
+              --output_test_mod2)
+                  VIASH_PAR_OUTPUT_TEST_MOD2="$2"
+                  shift 2
+                  ;;
+              --output_test_mod2=*)
+                  VIASH_PAR_OUTPUT_TEST_MOD2=$(ViashRemoveFlags "$1")
+                  shift 1
+                  ;;
+              --output_test_sol)
+                  VIASH_PAR_OUTPUT_TEST_SOL="$2"
+                  shift 2
+                  ;;
+              --output_test_sol=*)
+                  VIASH_PAR_OUTPUT_TEST_SOL=$(ViashRemoveFlags "$1")
                   shift 1
                   ;;
               ---setup)
@@ -637,16 +712,28 @@ functionality:
         ViashError '--input_mod2' is a required argument. Use "--help" to get more information on the parameters.
         exit 1
       fi
-      if [ -z "$VIASH_PAR_OUTPUT_MOD1" ]; then
-        ViashError '--output_mod1' is a required argument. Use "--help" to get more information on the parameters.
+      if [ -z "$VIASH_PAR_OUTPUT_TRAIN_MOD1" ]; then
+        ViashError '--output_train_mod1' is a required argument. Use "--help" to get more information on the parameters.
         exit 1
       fi
-      if [ -z "$VIASH_PAR_OUTPUT_MOD2" ]; then
-        ViashError '--output_mod2' is a required argument. Use "--help" to get more information on the parameters.
+      if [ -z "$VIASH_PAR_OUTPUT_TRAIN_MOD2" ]; then
+        ViashError '--output_train_mod2' is a required argument. Use "--help" to get more information on the parameters.
         exit 1
       fi
-      if [ -z "$VIASH_PAR_OUTPUT_SOLUTION" ]; then
-        ViashError '--output_solution' is a required argument. Use "--help" to get more information on the parameters.
+      if [ -z "$VIASH_PAR_OUTPUT_TRAIN_SOL" ]; then
+        ViashError '--output_train_sol' is a required argument. Use "--help" to get more information on the parameters.
+        exit 1
+      fi
+      if [ -z "$VIASH_PAR_OUTPUT_TEST_MOD1" ]; then
+        ViashError '--output_test_mod1' is a required argument. Use "--help" to get more information on the parameters.
+        exit 1
+      fi
+      if [ -z "$VIASH_PAR_OUTPUT_TEST_MOD2" ]; then
+        ViashError '--output_test_mod2' is a required argument. Use "--help" to get more information on the parameters.
+        exit 1
+      fi
+      if [ -z "$VIASH_PAR_OUTPUT_TEST_SOL" ]; then
+        ViashError '--output_test_sol' is a required argument. Use "--help" to get more information on the parameters.
         exit 1
       fi
       
@@ -662,17 +749,29 @@ functionality:
         VIASH_EXTRA_MOUNTS="$VIASH_EXTRA_MOUNTS $(ViashAutodetectMountArg "$VIASH_PAR_INPUT_MOD2")"
         VIASH_PAR_INPUT_MOD2=$(ViashAutodetectMount "$VIASH_PAR_INPUT_MOD2")
       fi
-      if [ ! -z "$VIASH_PAR_OUTPUT_MOD1" ]; then
-        VIASH_EXTRA_MOUNTS="$VIASH_EXTRA_MOUNTS $(ViashAutodetectMountArg "$VIASH_PAR_OUTPUT_MOD1")"
-        VIASH_PAR_OUTPUT_MOD1=$(ViashAutodetectMount "$VIASH_PAR_OUTPUT_MOD1")
+      if [ ! -z "$VIASH_PAR_OUTPUT_TRAIN_MOD1" ]; then
+        VIASH_EXTRA_MOUNTS="$VIASH_EXTRA_MOUNTS $(ViashAutodetectMountArg "$VIASH_PAR_OUTPUT_TRAIN_MOD1")"
+        VIASH_PAR_OUTPUT_TRAIN_MOD1=$(ViashAutodetectMount "$VIASH_PAR_OUTPUT_TRAIN_MOD1")
       fi
-      if [ ! -z "$VIASH_PAR_OUTPUT_MOD2" ]; then
-        VIASH_EXTRA_MOUNTS="$VIASH_EXTRA_MOUNTS $(ViashAutodetectMountArg "$VIASH_PAR_OUTPUT_MOD2")"
-        VIASH_PAR_OUTPUT_MOD2=$(ViashAutodetectMount "$VIASH_PAR_OUTPUT_MOD2")
+      if [ ! -z "$VIASH_PAR_OUTPUT_TRAIN_MOD2" ]; then
+        VIASH_EXTRA_MOUNTS="$VIASH_EXTRA_MOUNTS $(ViashAutodetectMountArg "$VIASH_PAR_OUTPUT_TRAIN_MOD2")"
+        VIASH_PAR_OUTPUT_TRAIN_MOD2=$(ViashAutodetectMount "$VIASH_PAR_OUTPUT_TRAIN_MOD2")
       fi
-      if [ ! -z "$VIASH_PAR_OUTPUT_SOLUTION" ]; then
-        VIASH_EXTRA_MOUNTS="$VIASH_EXTRA_MOUNTS $(ViashAutodetectMountArg "$VIASH_PAR_OUTPUT_SOLUTION")"
-        VIASH_PAR_OUTPUT_SOLUTION=$(ViashAutodetectMount "$VIASH_PAR_OUTPUT_SOLUTION")
+      if [ ! -z "$VIASH_PAR_OUTPUT_TRAIN_SOL" ]; then
+        VIASH_EXTRA_MOUNTS="$VIASH_EXTRA_MOUNTS $(ViashAutodetectMountArg "$VIASH_PAR_OUTPUT_TRAIN_SOL")"
+        VIASH_PAR_OUTPUT_TRAIN_SOL=$(ViashAutodetectMount "$VIASH_PAR_OUTPUT_TRAIN_SOL")
+      fi
+      if [ ! -z "$VIASH_PAR_OUTPUT_TEST_MOD1" ]; then
+        VIASH_EXTRA_MOUNTS="$VIASH_EXTRA_MOUNTS $(ViashAutodetectMountArg "$VIASH_PAR_OUTPUT_TEST_MOD1")"
+        VIASH_PAR_OUTPUT_TEST_MOD1=$(ViashAutodetectMount "$VIASH_PAR_OUTPUT_TEST_MOD1")
+      fi
+      if [ ! -z "$VIASH_PAR_OUTPUT_TEST_MOD2" ]; then
+        VIASH_EXTRA_MOUNTS="$VIASH_EXTRA_MOUNTS $(ViashAutodetectMountArg "$VIASH_PAR_OUTPUT_TEST_MOD2")"
+        VIASH_PAR_OUTPUT_TEST_MOD2=$(ViashAutodetectMount "$VIASH_PAR_OUTPUT_TEST_MOD2")
+      fi
+      if [ ! -z "$VIASH_PAR_OUTPUT_TEST_SOL" ]; then
+        VIASH_EXTRA_MOUNTS="$VIASH_EXTRA_MOUNTS $(ViashAutodetectMountArg "$VIASH_PAR_OUTPUT_TEST_SOL")"
+        VIASH_PAR_OUTPUT_TEST_SOL=$(ViashAutodetectMount "$VIASH_PAR_OUTPUT_TEST_SOL")
       fi
       
       # Always mount the resource directory
@@ -686,14 +785,23 @@ functionality:
       # change file ownership
       function viash_perform_chown {
         
-        if [ ! -z "$VIASH_PAR_OUTPUT_MOD1" ]; then
-          eval docker run --entrypoint=chown -i --rm $VIASH_EXTRA_MOUNTS openproblems/match_modality_datasets_censor_dataset:main_build "$(id -u):$(id -g)" --silent --recursive "$VIASH_PAR_OUTPUT_MOD1"
+        if [ ! -z "$VIASH_PAR_OUTPUT_TRAIN_MOD1" ]; then
+          eval docker run --entrypoint=chown -i --rm $VIASH_EXTRA_MOUNTS openproblems/match_modality_datasets_censor_dataset:main_build "$(id -u):$(id -g)" --silent --recursive "$VIASH_PAR_OUTPUT_TRAIN_MOD1"
         fi
-        if [ ! -z "$VIASH_PAR_OUTPUT_MOD2" ]; then
-          eval docker run --entrypoint=chown -i --rm $VIASH_EXTRA_MOUNTS openproblems/match_modality_datasets_censor_dataset:main_build "$(id -u):$(id -g)" --silent --recursive "$VIASH_PAR_OUTPUT_MOD2"
+        if [ ! -z "$VIASH_PAR_OUTPUT_TRAIN_MOD2" ]; then
+          eval docker run --entrypoint=chown -i --rm $VIASH_EXTRA_MOUNTS openproblems/match_modality_datasets_censor_dataset:main_build "$(id -u):$(id -g)" --silent --recursive "$VIASH_PAR_OUTPUT_TRAIN_MOD2"
         fi
-        if [ ! -z "$VIASH_PAR_OUTPUT_SOLUTION" ]; then
-          eval docker run --entrypoint=chown -i --rm $VIASH_EXTRA_MOUNTS openproblems/match_modality_datasets_censor_dataset:main_build "$(id -u):$(id -g)" --silent --recursive "$VIASH_PAR_OUTPUT_SOLUTION"
+        if [ ! -z "$VIASH_PAR_OUTPUT_TRAIN_SOL" ]; then
+          eval docker run --entrypoint=chown -i --rm $VIASH_EXTRA_MOUNTS openproblems/match_modality_datasets_censor_dataset:main_build "$(id -u):$(id -g)" --silent --recursive "$VIASH_PAR_OUTPUT_TRAIN_SOL"
+        fi
+        if [ ! -z "$VIASH_PAR_OUTPUT_TEST_MOD1" ]; then
+          eval docker run --entrypoint=chown -i --rm $VIASH_EXTRA_MOUNTS openproblems/match_modality_datasets_censor_dataset:main_build "$(id -u):$(id -g)" --silent --recursive "$VIASH_PAR_OUTPUT_TEST_MOD1"
+        fi
+        if [ ! -z "$VIASH_PAR_OUTPUT_TEST_MOD2" ]; then
+          eval docker run --entrypoint=chown -i --rm $VIASH_EXTRA_MOUNTS openproblems/match_modality_datasets_censor_dataset:main_build "$(id -u):$(id -g)" --silent --recursive "$VIASH_PAR_OUTPUT_TEST_MOD2"
+        fi
+        if [ ! -z "$VIASH_PAR_OUTPUT_TEST_SOL" ]; then
+          eval docker run --entrypoint=chown -i --rm $VIASH_EXTRA_MOUNTS openproblems/match_modality_datasets_censor_dataset:main_build "$(id -u):$(id -g)" --silent --recursive "$VIASH_PAR_OUTPUT_TEST_SOL"
         fi
       }
       trap viash_perform_chown EXIT
@@ -708,9 +816,8 @@ functionality:
       trap clean_up EXIT
       cat > "\$tempscript" << 'VIASHMAIN'
       print("Loading dependencies")
-      import anndata
+      import anndata as ad
       import random
-      import pandas as pd
       import numpy as np
       import scipy.sparse
       
@@ -719,9 +826,12 @@ functionality:
       par = {
         'input_mod1': $( if [ ! -z ${VIASH_PAR_INPUT_MOD1+x} ]; then echo "'$VIASH_PAR_INPUT_MOD1'"; else echo None; fi ),
         'input_mod2': $( if [ ! -z ${VIASH_PAR_INPUT_MOD2+x} ]; then echo "'$VIASH_PAR_INPUT_MOD2'"; else echo None; fi ),
-        'output_mod1': $( if [ ! -z ${VIASH_PAR_OUTPUT_MOD1+x} ]; then echo "'$VIASH_PAR_OUTPUT_MOD1'"; else echo None; fi ),
-        'output_mod2': $( if [ ! -z ${VIASH_PAR_OUTPUT_MOD2+x} ]; then echo "'$VIASH_PAR_OUTPUT_MOD2'"; else echo None; fi ),
-        'output_solution': $( if [ ! -z ${VIASH_PAR_OUTPUT_SOLUTION+x} ]; then echo "'$VIASH_PAR_OUTPUT_SOLUTION'"; else echo None; fi )
+        'output_train_mod1': $( if [ ! -z ${VIASH_PAR_OUTPUT_TRAIN_MOD1+x} ]; then echo "'$VIASH_PAR_OUTPUT_TRAIN_MOD1'"; else echo None; fi ),
+        'output_train_mod2': $( if [ ! -z ${VIASH_PAR_OUTPUT_TRAIN_MOD2+x} ]; then echo "'$VIASH_PAR_OUTPUT_TRAIN_MOD2'"; else echo None; fi ),
+        'output_train_sol': $( if [ ! -z ${VIASH_PAR_OUTPUT_TRAIN_SOL+x} ]; then echo "'$VIASH_PAR_OUTPUT_TRAIN_SOL'"; else echo None; fi ),
+        'output_test_mod1': $( if [ ! -z ${VIASH_PAR_OUTPUT_TEST_MOD1+x} ]; then echo "'$VIASH_PAR_OUTPUT_TEST_MOD1'"; else echo None; fi ),
+        'output_test_mod2': $( if [ ! -z ${VIASH_PAR_OUTPUT_TEST_MOD2+x} ]; then echo "'$VIASH_PAR_OUTPUT_TEST_MOD2'"; else echo None; fi ),
+        'output_test_sol': $( if [ ! -z ${VIASH_PAR_OUTPUT_TEST_SOL+x} ]; then echo "'$VIASH_PAR_OUTPUT_TEST_SOL'"; else echo None; fi )
       }
       
       resources_dir = '$VIASH_RESOURCES_DIR'
@@ -729,46 +839,80 @@ functionality:
       # VIASH END
       
       print("Reading input data")
-      mod1 = anndata.read_h5ad(par["input_mod1"])
-      mod2 = anndata.read_h5ad(par["input_mod2"])
+      mod1 = ad.read_h5ad(par["input_mod1"])
+      mod2 = ad.read_h5ad(par["input_mod2"])
       new_dataset_id = mod1.uns["dataset_id"] + "_MM"
       
-      print("Shuffling rows of mod2")
-      pairings = scipy.sparse.spdiags(np.full(mod1.shape[0], 1), diags=0, m=mod1.shape[0], n=mod2.shape[0], format="csr")
+      print("Shuffling train cells")
+      train_mod1_ix = np.where(mod1.obs["is_train"])[0]
+      train_mod2_ix = train_mod1_ix.copy()
+      random.shuffle(train_mod2_ix)
+      train_mod1 = mod1[train_mod1_ix, :]
+      train_mod2 = mod2[train_mod2_ix, :]
       
-      # Generate the indices partition
-      shuffle_cells = list(range(mod1.shape[0]))
-      random.shuffle(shuffle_cells)
+      print("Shuffling test cells")
+      test_mod1_ix = np.where(~mod1.obs["is_train"])[0]
+      test_mod2_ix = test_mod1_ix.copy()
+      random.shuffle(test_mod2_ix)
+      test_mod1 = mod1[test_mod1_ix, :]
+      test_mod2 = mod2[test_mod2_ix, :]
       
-      print("Creating output objects")
+      
+      print("Creating mod1 outputs")
       desired_var1_cols = [x for x in ["gene_ids", "feature_types"] if x in mod1.var.columns]
-      out_mod1 = anndata.AnnData(
-          X=mod1.X,
+      out_train_mod1 = ad.AnnData(
+          X=train_mod1.X,
           var=mod1.var[desired_var1_cols],
           uns={ "dataset_id": new_dataset_id },
-          dtype="float32",
       )
-      out_mod1.X.sort_indices()
+      out_train_mod1.X.sort_indices()
+      out_test_mod1 = ad.AnnData(
+          X=test_mod1.X,
+          var=mod1.var[desired_var1_cols],
+          uns={ "dataset_id": new_dataset_id },
+      )
+      out_test_mod1.X.sort_indices()
       
+      print("Creating mod2 outputs")
       desired_var2_cols = [x for x in ["gene_ids", "feature_types"] if x in mod2.var.columns]
-      out_mod2 = anndata.AnnData(
-          X=mod2.X[shuffle_cells, :],
+      out_train_mod2 = ad.AnnData(
+          X=train_mod2.X,
           var=mod2.var[desired_var2_cols],
+          uns={ "dataset_id": new_dataset_id },
+      )
+      out_train_mod2.X.sort_indices()
+      out_test_mod2 = ad.AnnData(
+          X=test_mod2.X,
+          var=mod2.var[desired_var2_cols],
+          uns={ "dataset_id": new_dataset_id },
+      )
+      out_test_mod2.X.sort_indices()
+      
+      print("Creating solution outputs")
+      out_train_sol_mat = scipy.sparse.csr_matrix(
+        (np.ones(train_mod1_ix.size), (train_mod1_ix, train_mod2_ix))
+      )
+      out_train_sol = ad.AnnData(
+          X=out_train_sol_mat,
           uns={ "dataset_id": new_dataset_id },
           dtype="float32",
       )
-      out_mod2.X.sort_indices()
-      
-      out_solution = anndata.AnnData(
-          X=pairings[:, shuffle_cells],
+      out_test_sol_mat = scipy.sparse.csr_matrix(
+        (np.ones(test_mod1_ix.size), (test_mod1_ix, test_mod2_ix))
+      )
+      out_test_sol = ad.AnnData(
+          X=out_test_sol_mat,
           uns={ "dataset_id": new_dataset_id },
           dtype="float32"
       )
       
       print("Writing output objects to file")
-      out_mod1.write_h5ad(filename=par["output_mod1"], compression="gzip")
-      out_mod2.write_h5ad(filename=par["output_mod2"], compression="gzip")
-      out_solution.write_h5ad(filename=par["output_solution"], compression="gzip")
+      out_train_mod1.write_h5ad(filename=par["output_train_mod1"], compression="gzip")
+      out_train_mod2.write_h5ad(filename=par["output_train_mod2"], compression="gzip")
+      out_train_sol.write_h5ad(filename=par["output_train_sol"], compression="gzip")
+      out_test_mod1.write_h5ad(filename=par["output_test_mod1"], compression="gzip")
+      out_test_mod2.write_h5ad(filename=par["output_test_mod2"], compression="gzip")
+      out_test_sol.write_h5ad(filename=par["output_test_sol"], compression="gzip")
       VIASHMAIN
       PATH="$VIASH_RESOURCES_DIR:\$PATH"
       
@@ -822,5 +966,5 @@ info:
   output: "target/docker/match_modality_datasets/censor_dataset"
   executable: "target/docker/match_modality_datasets/censor_dataset/censor_dataset"
   viash_version: "0.5.1"
-  git_commit: "0aee0875ed69d4a4c5d0907f6363bb8170fcdfa9"
+  git_commit: "6f575b2a9df44c62b311887a52b1f9c16a9f6a1c"
   git_remote: "https://github.com/openproblems-bio/neurips2021_multimodal_viash"
