deploy: 519f6758b46341280ee75a287b2af5dc228d3577

diff --git a/target/docker/common/create_starter_kit/viash.yaml b/target/docker/common/create_starter_kit/viash.yaml
--- a/target/docker/common/create_starter_kit/viash.yaml
+++ b/target/docker/common/create_starter_kit/viash.yaml
@@ -53,6 +53,14 @@ functionality:
     multiple: false
     multiple_sep: ":"
   - type: "string"
+    name: "--block_starter"
+    alternatives: []
+    example: "par <- list("
+    required: true
+    direction: "Input"
+    multiple: false
+    multiple_sep: ":"
+  - type: "string"
     name: "--evalai_phase"
     alternatives: []
     example: "2276"
@@ -280,6 +288,12 @@ functionality:
         echo ""
       
       
+        echo "   --block_starter"
+        echo "        type: string, required parameter"
+        echo "        example: par <- list("
+        echo ""
+      
+      
         echo "   --evalai_phase"
         echo "        type: string, required parameter"
         echo "        example: 2276"
@@ -466,7 +480,7 @@ functionality:
       #   ViashDockerFile
       function ViashDockerfile {
         cat << 'VIASHDOCKER'
-      FROM ubuntu:18.04
+      FROM dataintuitive/viash:latest
       
       RUN :
       VIASHDOCKER
@@ -657,6 +671,14 @@ functionality:
                   VIASH_PAR_LANGUAGE_NAME=$(ViashRemoveFlags "$1")
                   shift 1
                   ;;
+              --block_starter)
+                  VIASH_PAR_BLOCK_STARTER="$2"
+                  shift 2
+                  ;;
+              --block_starter=*)
+                  VIASH_PAR_BLOCK_STARTER=$(ViashRemoveFlags "$1")
+                  shift 1
+                  ;;
               --evalai_phase)
                   VIASH_PAR_EVALAI_PHASE="$2"
                   shift 2
@@ -764,6 +786,10 @@ functionality:
         ViashError '--language_name' is a required argument. Use "--help" to get more information on the parameters.
         exit 1
       fi
+      if [ -z "$VIASH_PAR_BLOCK_STARTER" ]; then
+        ViashError '--block_starter' is a required argument. Use "--help" to get more information on the parameters.
+        exit 1
+      fi
       if [ -z "$VIASH_PAR_EVALAI_PHASE" ]; then
         ViashError '--evalai_phase' is a required argument. Use "--help" to get more information on the parameters.
         exit 1
@@ -833,6 +859,7 @@ functionality:
       par_task_name='$VIASH_PAR_TASK_NAME'
       par_language='$VIASH_PAR_LANGUAGE'
       par_language_name='$VIASH_PAR_LANGUAGE_NAME'
+      par_block_starter='$VIASH_PAR_BLOCK_STARTER'
       par_evalai_phase='$VIASH_PAR_EVALAI_PHASE'
       par_memory='$VIASH_PAR_MEMORY'
       par_time='$VIASH_PAR_TIME'
@@ -866,6 +893,11 @@ functionality:
       sed -i "s#\\\\\\\$par_time#\$par_time#g" \$output_dir/*
       sed -i "s#\\\\\\\$par_cpus#\$par_cpus#g" \$output_dir/*
       sed -i "s#\\\\\\\$par_pipeline_version#\$par_pipeline_version#g" \$output_dir/*
+      sed -i "s#\\\\\\\$par_block_starter#\$par_block_starter#g" \$output_dir/*
+      
+      echo run viash dockerfile
+      dockerfile=\$(viash run \$par_input_dir/config.vsh.yaml -- ---dockerfile | sed 's#^#\\t#' | sed ':a;N;\$!ba;s/\\n/\\\\n/g' | sed 's#&#\\\\\\&#g')
+      sed -i "s~\\\\\\\$codeblock_dockerfile~\$dockerfile~g" \$output_dir/*
       
       echo copy scripts
       cp \$par_input_dir/* \$output_dir
@@ -895,7 +927,7 @@ functionality:
 platform:
   type: "docker"
   id: "docker"
-  image: "ubuntu:18.04"
+  image: "dataintuitive/viash"
   target_registry: "openproblems"
   namespace_separator: "_"
   resolve_volume: "Automatic"
@@ -910,5 +942,5 @@ info:
   output: "target/docker/common/create_starter_kit"
   executable: "target/docker/common/create_starter_kit/create_starter_kit"
   viash_version: "0.5.1"
-  git_commit: "76dab809a0b001bd7f8248317a39b31f741badd0"
+  git_commit: "519f6758b46341280ee75a287b2af5dc228d3577"
   git_remote: "https://github.com/openproblems-bio/neurips2021_multimodal_viash"
diff --git a/target/nextflow/common/create_starter_kit/create_starter_kit b/target/nextflow/common/create_starter_kit/create_starter_kit
--- a/target/nextflow/common/create_starter_kit/create_starter_kit
+++ b/target/nextflow/common/create_starter_kit/create_starter_kit
@@ -174,6 +174,12 @@ function ViashHelp {
   echo ""
 
 
+  echo "   --block_starter"
+  echo "        type: string, required parameter"
+  echo "        example: par <- list("
+  echo ""
+
+
   echo "   --evalai_phase"
   echo "        type: string, required parameter"
   echo "        example: 2276"
@@ -280,6 +286,14 @@ while [[ $# -gt 0 ]]; do
             VIASH_PAR_LANGUAGE_NAME=$(ViashRemoveFlags "$1")
             shift 1
             ;;
+        --block_starter)
+            VIASH_PAR_BLOCK_STARTER="$2"
+            shift 2
+            ;;
+        --block_starter=*)
+            VIASH_PAR_BLOCK_STARTER=$(ViashRemoveFlags "$1")
+            shift 1
+            ;;
         --evalai_phase)
             VIASH_PAR_EVALAI_PHASE="$2"
             shift 2
@@ -362,6 +376,10 @@ if [ -z "$VIASH_PAR_LANGUAGE_NAME" ]; then
   ViashError '--language_name' is a required argument. Use "--help" to get more information on the parameters.
   exit 1
 fi
+if [ -z "$VIASH_PAR_BLOCK_STARTER" ]; then
+  ViashError '--block_starter' is a required argument. Use "--help" to get more information on the parameters.
+  exit 1
+fi
 if [ -z "$VIASH_PAR_EVALAI_PHASE" ]; then
   ViashError '--evalai_phase' is a required argument. Use "--help" to get more information on the parameters.
   exit 1
@@ -402,6 +420,7 @@ par_task='$VIASH_PAR_TASK'
 par_task_name='$VIASH_PAR_TASK_NAME'
 par_language='$VIASH_PAR_LANGUAGE'
 par_language_name='$VIASH_PAR_LANGUAGE_NAME'
+par_block_starter='$VIASH_PAR_BLOCK_STARTER'
 par_evalai_phase='$VIASH_PAR_EVALAI_PHASE'
 par_memory='$VIASH_PAR_MEMORY'
 par_time='$VIASH_PAR_TIME'
@@ -435,6 +454,11 @@ sed -i "s#\\\\\\\$par_memory#\$par_memory#g" \$output_dir/*
 sed -i "s#\\\\\\\$par_time#\$par_time#g" \$output_dir/*
 sed -i "s#\\\\\\\$par_cpus#\$par_cpus#g" \$output_dir/*
 sed -i "s#\\\\\\\$par_pipeline_version#\$par_pipeline_version#g" \$output_dir/*
+sed -i "s#\\\\\\\$par_block_starter#\$par_block_starter#g" \$output_dir/*
+
+echo run viash dockerfile
+dockerfile=\$(viash run \$par_input_dir/config.vsh.yaml -- ---dockerfile | sed 's#^#\\t#' | sed ':a;N;\$!ba;s/\\n/\\\\n/g' | sed 's#&#\\\\\\&#g')
+sed -i "s~\\\\\\\$codeblock_dockerfile~\$dockerfile~g" \$output_dir/*
 
 echo copy scripts
 cp \$par_input_dir/* \$output_dir
diff --git a/target/nextflow/common/create_starter_kit/viash.yaml b/target/nextflow/common/create_starter_kit/viash.yaml
--- a/target/nextflow/common/create_starter_kit/viash.yaml
+++ b/target/nextflow/common/create_starter_kit/viash.yaml
@@ -53,6 +53,14 @@ functionality:
     multiple: false
     multiple_sep: ":"
   - type: "string"
+    name: "--block_starter"
+    alternatives: []
+    example: "par <- list("
+    required: true
+    direction: "Input"
+    multiple: false
+    multiple_sep: ":"
+  - type: "string"
     name: "--evalai_phase"
     alternatives: []
     example: "2276"
@@ -280,6 +288,12 @@ functionality:
         echo ""
       
       
+        echo "   --block_starter"
+        echo "        type: string, required parameter"
+        echo "        example: par <- list("
+        echo ""
+      
+      
         echo "   --evalai_phase"
         echo "        type: string, required parameter"
         echo "        example: 2276"
@@ -386,6 +400,14 @@ functionality:
                   VIASH_PAR_LANGUAGE_NAME=$(ViashRemoveFlags "$1")
                   shift 1
                   ;;
+              --block_starter)
+                  VIASH_PAR_BLOCK_STARTER="$2"
+                  shift 2
+                  ;;
+              --block_starter=*)
+                  VIASH_PAR_BLOCK_STARTER=$(ViashRemoveFlags "$1")
+                  shift 1
+                  ;;
               --evalai_phase)
                   VIASH_PAR_EVALAI_PHASE="$2"
                   shift 2
@@ -468,6 +490,10 @@ functionality:
         ViashError '--language_name' is a required argument. Use "--help" to get more information on the parameters.
         exit 1
       fi
+      if [ -z "$VIASH_PAR_BLOCK_STARTER" ]; then
+        ViashError '--block_starter' is a required argument. Use "--help" to get more information on the parameters.
+        exit 1
+      fi
       if [ -z "$VIASH_PAR_EVALAI_PHASE" ]; then
         ViashError '--evalai_phase' is a required argument. Use "--help" to get more information on the parameters.
         exit 1
@@ -508,6 +534,7 @@ functionality:
       par_task_name='$VIASH_PAR_TASK_NAME'
       par_language='$VIASH_PAR_LANGUAGE'
       par_language_name='$VIASH_PAR_LANGUAGE_NAME'
+      par_block_starter='$VIASH_PAR_BLOCK_STARTER'
       par_evalai_phase='$VIASH_PAR_EVALAI_PHASE'
       par_memory='$VIASH_PAR_MEMORY'
       par_time='$VIASH_PAR_TIME'
@@ -541,6 +568,11 @@ functionality:
       sed -i "s#\\\\\\\$par_time#\$par_time#g" \$output_dir/*
       sed -i "s#\\\\\\\$par_cpus#\$par_cpus#g" \$output_dir/*
       sed -i "s#\\\\\\\$par_pipeline_version#\$par_pipeline_version#g" \$output_dir/*
+      sed -i "s#\\\\\\\$par_block_starter#\$par_block_starter#g" \$output_dir/*
+      
+      echo run viash dockerfile
+      dockerfile=\$(viash run \$par_input_dir/config.vsh.yaml -- ---dockerfile | sed 's#^#\\t#' | sed ':a;N;\$!ba;s/\\n/\\\\n/g' | sed 's#&#\\\\\\&#g')
+      sed -i "s~\\\\\\\$codeblock_dockerfile~\$dockerfile~g" \$output_dir/*
       
       echo copy scripts
       cp \$par_input_dir/* \$output_dir
@@ -575,6 +607,7 @@ functionality:
           create_starter_kit__task_name = "viash_no_value"
           create_starter_kit__language = "viash_no_value"
           create_starter_kit__language_name = "viash_no_value"
+          create_starter_kit__block_starter = "viash_no_value"
           create_starter_kit__evalai_phase = "viash_no_value"
           create_starter_kit__memory = "16 GB"
           create_starter_kit__time = "10m"
@@ -650,6 +683,17 @@ functionality:
                 multiple_sep = ":"
                 value = "${params.create_starter_kit__language_name}"
                 example = "R"
+              }
+              block_starter {
+                name = "block_starter"
+                otype = "--"
+                required = true
+                type = "string"
+                direction = "Input"
+                multiple = false
+                multiple_sep = ":"
+                value = "${params.create_starter_kit__block_starter}"
+                example = "par <- list("
               }
               evalai_phase {
                 name = "evalai_phase"
@@ -1067,5 +1111,5 @@ info:
   output: "target/nextflow/common/create_starter_kit"
   executable: "target/nextflow/common/create_starter_kit/create_starter_kit"
   viash_version: "0.5.1"
-  git_commit: "76dab809a0b001bd7f8248317a39b31f741badd0"
+  git_commit: "519f6758b46341280ee75a287b2af5dc228d3577"
   git_remote: "https://github.com/openproblems-bio/neurips2021_multimodal_viash"
