deploy: 53cafda52f02612563bed618cf8b7e232c59d4fa

diff --git a/target/docker/common_datasets/download_azimuth_dataset/viash.yaml b/target/docker/common_datasets/download_azimuth_dataset/viash.yaml
--- a/target/docker/common_datasets/download_azimuth_dataset/viash.yaml
+++ b/target/docker/common_datasets/download_azimuth_dataset/viash.yaml
@@ -38,6 +38,15 @@ functionality:
     direction: "Input"
     multiple: false
     multiple_sep: ":"
+  - type: "string"
+    name: "--organism"
+    alternatives: []
+    description: "The organism of the dataset"
+    example: "human"
+    required: true
+    direction: "Input"
+    multiple: false
+    multiple_sep: ":"
   - type: "file"
     name: "--output_rna"
     alternatives: []
@@ -233,6 +242,13 @@ functionality:
         echo "        type: string, required parameter"
         echo "        example: https://www.ncbi.nlm.nih.gov/geo/download/?acc=GSE164378&format=file&file=GSE164378%5Fsc%2Emeta%2Edata%5F3P%2Ecsv%2Egz"
         echo "        Location URL to the GEO meta data file"
+        echo ""
+      
+      
+        echo "   --organism"
+        echo "        type: string, required parameter"
+        echo "        example: human"
+        echo "        The organism of the dataset"
         echo ""
       
       
@@ -577,6 +593,14 @@ functionality:
                   VIASH_PAR_INPUT_META=$(ViashRemoveFlags "$1")
                   shift 1
                   ;;
+              --organism)
+                  VIASH_PAR_ORGANISM="$2"
+                  shift 2
+                  ;;
+              --organism=*)
+                  VIASH_PAR_ORGANISM=$(ViashRemoveFlags "$1")
+                  shift 1
+                  ;;
               --output_rna)
                   VIASH_PAR_OUTPUT_RNA="$2"
                   shift 2
@@ -642,6 +666,10 @@ functionality:
       fi
       if [ -z "$VIASH_PAR_INPUT_META" ]; then
         ViashError '--input_meta' is a required argument. Use "--help" to get more information on the parameters.
+        exit 1
+      fi
+      if [ -z "$VIASH_PAR_ORGANISM" ]; then
+        ViashError '--organism' is a required argument. Use "--help" to get more information on the parameters.
         exit 1
       fi
       if [ -z "$VIASH_PAR_OUTPUT_RNA" ]; then
@@ -713,6 +741,7 @@ functionality:
         'id': $( if [ ! -z ${VIASH_PAR_ID+x} ]; then echo "'$VIASH_PAR_ID'"; else echo None; fi ),
         'input_count': $( if [ ! -z ${VIASH_PAR_INPUT_COUNT+x} ]; then echo "'$VIASH_PAR_INPUT_COUNT'"; else echo None; fi ),
         'input_meta': $( if [ ! -z ${VIASH_PAR_INPUT_META+x} ]; then echo "'$VIASH_PAR_INPUT_META'"; else echo None; fi ),
+        'organism': $( if [ ! -z ${VIASH_PAR_ORGANISM+x} ]; then echo "'$VIASH_PAR_ORGANISM'"; else echo None; fi ),
         'output_rna': $( if [ ! -z ${VIASH_PAR_OUTPUT_RNA+x} ]; then echo "'$VIASH_PAR_OUTPUT_RNA'"; else echo None; fi ),
         'output_mod2': $( if [ ! -z ${VIASH_PAR_OUTPUT_MOD2+x} ]; then echo "'$VIASH_PAR_OUTPUT_MOD2'"; else echo None; fi )
       }
@@ -796,7 +825,7 @@ functionality:
       protein.var['feature_types'] = "ADT"
       
       # set uns 
-      uns = { "dataset_id" : par["id"] }
+      uns = { "dataset_id" : par["id"], "organism" : par["organism"] }
       adata.uns = uns
       protein.uns = uns
       
@@ -860,5 +889,5 @@ info:
   output: "target/docker/common_datasets/download_azimuth_dataset"
   executable: "target/docker/common_datasets/download_azimuth_dataset/download_azimuth_dataset"
   viash_version: "0.5.1"
-  git_commit: "0ea195f52434e5eb89479a7be89b7d535bce4ad4"
+  git_commit: "53cafda52f02612563bed618cf8b7e232c59d4fa"
   git_remote: "https://github.com/openproblems-bio/neurips2021_multimodal_viash"
diff --git a/target/docker/common_datasets/download_babel_dataset/download_babel_datasets b/target/docker/common_datasets/download_babel_dataset/download_babel_datasets
--- a/target/docker/common_datasets/download_babel_dataset/download_babel_datasets
+++ b/target/docker/common_datasets/download_babel_dataset/download_babel_datasets
@@ -158,8 +158,15 @@ function ViashHelp {
 
   echo "   --input"
   echo "        type: string, required parameter"
-  echo "        example: https://www.ncbi.nlm.nih.gov/geo/download/?acc=GSE164378&format=file"
+  echo "        example: https://www.ncbi.nlm.nih.gov/geo/download/?acc=GSE166797&format=file"
   echo "        Location URL to the GEO raw counts tar file."
+  echo ""
+
+
+  echo "   --organism"
+  echo "        type: string, required parameter"
+  echo "        example: human"
+  echo "        The organism of the dataset"
   echo ""
 
 
@@ -496,6 +503,14 @@ while [[ $# -gt 0 ]]; do
             VIASH_PAR_INPUT=$(ViashRemoveFlags "$1")
             shift 1
             ;;
+        --organism)
+            VIASH_PAR_ORGANISM="$2"
+            shift 2
+            ;;
+        --organism=*)
+            VIASH_PAR_ORGANISM=$(ViashRemoveFlags "$1")
+            shift 1
+            ;;
         --output_rna)
             VIASH_PAR_OUTPUT_RNA="$2"
             shift 2
@@ -557,6 +572,10 @@ if [ -z "$VIASH_PAR_ID" ]; then
 fi
 if [ -z "$VIASH_PAR_INPUT" ]; then
   ViashError '--input' is a required argument. Use "--help" to get more information on the parameters.
+  exit 1
+fi
+if [ -z "$VIASH_PAR_ORGANISM" ]; then
+  ViashError '--organism' is a required argument. Use "--help" to get more information on the parameters.
   exit 1
 fi
 if [ -z "$VIASH_PAR_OUTPUT_RNA" ]; then
@@ -622,6 +641,7 @@ import scanpy as sc
 par = {
   'id': $( if [ ! -z ${VIASH_PAR_ID+x} ]; then echo "'$VIASH_PAR_ID'"; else echo None; fi ),
   'input': $( if [ ! -z ${VIASH_PAR_INPUT+x} ]; then echo "'$VIASH_PAR_INPUT'"; else echo None; fi ),
+  'organism': $( if [ ! -z ${VIASH_PAR_ORGANISM+x} ]; then echo "'$VIASH_PAR_ORGANISM'"; else echo None; fi ),
   'output_rna': $( if [ ! -z ${VIASH_PAR_OUTPUT_RNA+x} ]; then echo "'$VIASH_PAR_OUTPUT_RNA'"; else echo None; fi ),
   'output_mod2': $( if [ ! -z ${VIASH_PAR_OUTPUT_MOD2+x} ]; then echo "'$VIASH_PAR_OUTPUT_MOD2'"; else echo None; fi )
 }
@@ -668,7 +688,7 @@ adata_ATAC = comb[:, comb.var.feature_types == "Peaks"].copy()
 adata_RNA.var.feature_types = 'GEX'
 adata_ATAC.var.feature_types = 'ATAC'
 
-uns = { "dataset_id" : par["id"] }
+uns = { "dataset_id" : par["id"], "organism" : par["organism"] }
 adata_RNA.uns = uns
 adata_ATAC.uns = uns
 
diff --git a/target/docker/common_datasets/download_babel_dataset/viash.yaml b/target/docker/common_datasets/download_babel_dataset/viash.yaml
--- a/target/docker/common_datasets/download_babel_dataset/viash.yaml
+++ b/target/docker/common_datasets/download_babel_dataset/viash.yaml
@@ -24,7 +24,16 @@ functionality:
     name: "--input"
     alternatives: []
     description: "Location URL to the GEO raw counts tar file."
-    example: "https://www.ncbi.nlm.nih.gov/geo/download/?acc=GSE164378&format=file"
+    example: "https://www.ncbi.nlm.nih.gov/geo/download/?acc=GSE166797&format=file"
+    required: true
+    direction: "Input"
+    multiple: false
+    multiple_sep: ":"
+  - type: "string"
+    name: "--organism"
+    alternatives: []
+    description: "The organism of the dataset"
+    example: "human"
     required: true
     direction: "Input"
     multiple: false
@@ -212,8 +221,15 @@ functionality:
       
         echo "   --input"
         echo "        type: string, required parameter"
-        echo "        example: https://www.ncbi.nlm.nih.gov/geo/download/?acc=GSE164378&format=file"
+        echo "        example: https://www.ncbi.nlm.nih.gov/geo/download/?acc=GSE166797&format=file"
         echo "        Location URL to the GEO raw counts tar file."
+        echo ""
+      
+      
+        echo "   --organism"
+        echo "        type: string, required parameter"
+        echo "        example: human"
+        echo "        The organism of the dataset"
         echo ""
       
       
@@ -550,6 +566,14 @@ functionality:
                   VIASH_PAR_INPUT=$(ViashRemoveFlags "$1")
                   shift 1
                   ;;
+              --organism)
+                  VIASH_PAR_ORGANISM="$2"
+                  shift 2
+                  ;;
+              --organism=*)
+                  VIASH_PAR_ORGANISM=$(ViashRemoveFlags "$1")
+                  shift 1
+                  ;;
               --output_rna)
                   VIASH_PAR_OUTPUT_RNA="$2"
                   shift 2
@@ -611,6 +635,10 @@ functionality:
       fi
       if [ -z "$VIASH_PAR_INPUT" ]; then
         ViashError '--input' is a required argument. Use "--help" to get more information on the parameters.
+        exit 1
+      fi
+      if [ -z "$VIASH_PAR_ORGANISM" ]; then
+        ViashError '--organism' is a required argument. Use "--help" to get more information on the parameters.
         exit 1
       fi
       if [ -z "$VIASH_PAR_OUTPUT_RNA" ]; then
@@ -676,6 +704,7 @@ functionality:
       par = {
         'id': $( if [ ! -z ${VIASH_PAR_ID+x} ]; then echo "'$VIASH_PAR_ID'"; else echo None; fi ),
         'input': $( if [ ! -z ${VIASH_PAR_INPUT+x} ]; then echo "'$VIASH_PAR_INPUT'"; else echo None; fi ),
+        'organism': $( if [ ! -z ${VIASH_PAR_ORGANISM+x} ]; then echo "'$VIASH_PAR_ORGANISM'"; else echo None; fi ),
         'output_rna': $( if [ ! -z ${VIASH_PAR_OUTPUT_RNA+x} ]; then echo "'$VIASH_PAR_OUTPUT_RNA'"; else echo None; fi ),
         'output_mod2': $( if [ ! -z ${VIASH_PAR_OUTPUT_MOD2+x} ]; then echo "'$VIASH_PAR_OUTPUT_MOD2'"; else echo None; fi )
       }
@@ -722,7 +751,7 @@ functionality:
       adata_RNA.var.feature_types = 'GEX'
       adata_ATAC.var.feature_types = 'ATAC'
       
-      uns = { "dataset_id" : par["id"] }
+      uns = { "dataset_id" : par["id"], "organism" : par["organism"] }
       adata_RNA.uns = uns
       adata_ATAC.uns = uns
       
@@ -778,5 +807,5 @@ info:
   output: "target/docker/common_datasets/download_babel_dataset"
   executable: "target/docker/common_datasets/download_babel_dataset/download_babel_datasets"
   viash_version: "0.5.1"
-  git_commit: "0ea195f52434e5eb89479a7be89b7d535bce4ad4"
+  git_commit: "53cafda52f02612563bed618cf8b7e232c59d4fa"
   git_remote: "https://github.com/openproblems-bio/neurips2021_multimodal_viash"
diff --git a/target/docker/common_datasets/download_totalvi_spleen_lymph/download_totalvi_spleen_lymph b/target/docker/common_datasets/download_totalvi_spleen_lymph/download_totalvi_spleen_lymph
--- a/target/docker/common_datasets/download_totalvi_spleen_lymph/download_totalvi_spleen_lymph
+++ b/target/docker/common_datasets/download_totalvi_spleen_lymph/download_totalvi_spleen_lymph
@@ -163,6 +163,13 @@ function ViashHelp {
   echo ""
 
 
+  echo "   --organism"
+  echo "        type: string, required parameter"
+  echo "        example: mouse"
+  echo "        The organism of the dataset"
+  echo ""
+
+
   echo "   --output_rna"
   echo "        type: file, required parameter, output"
   echo "        example: output_rna.h5ad"
@@ -496,6 +503,14 @@ while [[ $# -gt 0 ]]; do
             VIASH_PAR_INPUT=$(ViashRemoveFlags "$1")
             shift 1
             ;;
+        --organism)
+            VIASH_PAR_ORGANISM="$2"
+            shift 2
+            ;;
+        --organism=*)
+            VIASH_PAR_ORGANISM=$(ViashRemoveFlags "$1")
+            shift 1
+            ;;
         --output_rna)
             VIASH_PAR_OUTPUT_RNA="$2"
             shift 2
@@ -557,6 +572,10 @@ if [ -z "$VIASH_PAR_ID" ]; then
 fi
 if [ -z "$VIASH_PAR_INPUT" ]; then
   ViashError '--input' is a required argument. Use "--help" to get more information on the parameters.
+  exit 1
+fi
+if [ -z "$VIASH_PAR_ORGANISM" ]; then
+  ViashError '--organism' is a required argument. Use "--help" to get more information on the parameters.
   exit 1
 fi
 if [ -z "$VIASH_PAR_OUTPUT_RNA" ]; then
@@ -623,6 +642,7 @@ from scipy import sparse
 par = {
   'id': $( if [ ! -z ${VIASH_PAR_ID+x} ]; then echo "'$VIASH_PAR_ID'"; else echo None; fi ),
   'input': $( if [ ! -z ${VIASH_PAR_INPUT+x} ]; then echo "'$VIASH_PAR_INPUT'"; else echo None; fi ),
+  'organism': $( if [ ! -z ${VIASH_PAR_ORGANISM+x} ]; then echo "'$VIASH_PAR_ORGANISM'"; else echo None; fi ),
   'output_rna': $( if [ ! -z ${VIASH_PAR_OUTPUT_RNA+x} ]; then echo "'$VIASH_PAR_OUTPUT_RNA'"; else echo None; fi ),
   'output_mod2': $( if [ ! -z ${VIASH_PAR_OUTPUT_MOD2+x} ]; then echo "'$VIASH_PAR_OUTPUT_MOD2'"; else echo None; fi )
 }
@@ -647,7 +667,7 @@ h5ad_temp.close()
 ###                     CREATE H5AD FOR BOTH MODALITIES                     ###
 ###############################################################################
 new_obs = adata.obs.rename(columns = {'cell_types': 'cell_type', 'batch_indices': 'batch'}, inplace = False)
-uns = { "dataset_id" : par["id"] }
+uns = { "dataset_id" : par["id"], "organism" : par["organism"] }
 
 print("Extracting RNA counts")
 adata_rna = anndata.AnnData(
diff --git a/target/docker/common_datasets/download_totalvi_spleen_lymph/viash.yaml b/target/docker/common_datasets/download_totalvi_spleen_lymph/viash.yaml
--- a/target/docker/common_datasets/download_totalvi_spleen_lymph/viash.yaml
+++ b/target/docker/common_datasets/download_totalvi_spleen_lymph/viash.yaml
@@ -29,6 +29,15 @@ functionality:
     direction: "Input"
     multiple: false
     multiple_sep: ":"
+  - type: "string"
+    name: "--organism"
+    alternatives: []
+    description: "The organism of the dataset"
+    example: "mouse"
+    required: true
+    direction: "Input"
+    multiple: false
+    multiple_sep: ":"
   - type: "file"
     name: "--output_rna"
     alternatives: []
@@ -214,6 +223,13 @@ functionality:
         echo "        type: string, required parameter"
         echo "        example: https://github.com/YosefLab/totalVI_reproducibility/raw/master/data/spleen_lymph_111.h5ad"
         echo "        Location URL to an h5ad file from the totalVI reproducibility github."
+        echo ""
+      
+      
+        echo "   --organism"
+        echo "        type: string, required parameter"
+        echo "        example: mouse"
+        echo "        The organism of the dataset"
         echo ""
       
       
@@ -550,6 +566,14 @@ functionality:
                   VIASH_PAR_INPUT=$(ViashRemoveFlags "$1")
                   shift 1
                   ;;
+              --organism)
+                  VIASH_PAR_ORGANISM="$2"
+                  shift 2
+                  ;;
+              --organism=*)
+                  VIASH_PAR_ORGANISM=$(ViashRemoveFlags "$1")
+                  shift 1
+                  ;;
               --output_rna)
                   VIASH_PAR_OUTPUT_RNA="$2"
                   shift 2
@@ -611,6 +635,10 @@ functionality:
       fi
       if [ -z "$VIASH_PAR_INPUT" ]; then
         ViashError '--input' is a required argument. Use "--help" to get more information on the parameters.
+        exit 1
+      fi
+      if [ -z "$VIASH_PAR_ORGANISM" ]; then
+        ViashError '--organism' is a required argument. Use "--help" to get more information on the parameters.
         exit 1
       fi
       if [ -z "$VIASH_PAR_OUTPUT_RNA" ]; then
@@ -677,6 +705,7 @@ functionality:
       par = {
         'id': $( if [ ! -z ${VIASH_PAR_ID+x} ]; then echo "'$VIASH_PAR_ID'"; else echo None; fi ),
         'input': $( if [ ! -z ${VIASH_PAR_INPUT+x} ]; then echo "'$VIASH_PAR_INPUT'"; else echo None; fi ),
+        'organism': $( if [ ! -z ${VIASH_PAR_ORGANISM+x} ]; then echo "'$VIASH_PAR_ORGANISM'"; else echo None; fi ),
         'output_rna': $( if [ ! -z ${VIASH_PAR_OUTPUT_RNA+x} ]; then echo "'$VIASH_PAR_OUTPUT_RNA'"; else echo None; fi ),
         'output_mod2': $( if [ ! -z ${VIASH_PAR_OUTPUT_MOD2+x} ]; then echo "'$VIASH_PAR_OUTPUT_MOD2'"; else echo None; fi )
       }
@@ -701,7 +730,7 @@ functionality:
       ###                     CREATE H5AD FOR BOTH MODALITIES                     ###
       ###############################################################################
       new_obs = adata.obs.rename(columns = {'cell_types': 'cell_type', 'batch_indices': 'batch'}, inplace = False)
-      uns = { "dataset_id" : par["id"] }
+      uns = { "dataset_id" : par["id"], "organism" : par["organism"] }
       
       print("Extracting RNA counts")
       adata_rna = anndata.AnnData(
@@ -783,5 +812,5 @@ info:
   output: "target/docker/common_datasets/download_totalvi_spleen_lymph"
   executable: "target/docker/common_datasets/download_totalvi_spleen_lymph/download_totalvi_spleen_lymph"
   viash_version: "0.5.1"
-  git_commit: "0ea195f52434e5eb89479a7be89b7d535bce4ad4"
+  git_commit: "53cafda52f02612563bed618cf8b7e232c59d4fa"
   git_remote: "https://github.com/openproblems-bio/neurips2021_multimodal_viash"
diff --git a/target/nextflow/common_datasets/download_azimuth_dataset/download_azimuth_dataset b/target/nextflow/common_datasets/download_azimuth_dataset/download_azimuth_dataset
--- a/target/nextflow/common_datasets/download_azimuth_dataset/download_azimuth_dataset
+++ b/target/nextflow/common_datasets/download_azimuth_dataset/download_azimuth_dataset
@@ -173,6 +173,13 @@ function ViashHelp {
   echo ""
 
 
+  echo "   --organism"
+  echo "        type: string, required parameter"
+  echo "        example: human"
+  echo "        The organism of the dataset"
+  echo ""
+
+
   echo "   --output_rna"
   echo "        type: file, required parameter, output"
   echo "        example: output_rna.h5ad"
@@ -241,6 +248,14 @@ while [[ $# -gt 0 ]]; do
             VIASH_PAR_INPUT_META=$(ViashRemoveFlags "$1")
             shift 1
             ;;
+        --organism)
+            VIASH_PAR_ORGANISM="$2"
+            shift 2
+            ;;
+        --organism=*)
+            VIASH_PAR_ORGANISM=$(ViashRemoveFlags "$1")
+            shift 1
+            ;;
         --output_rna)
             VIASH_PAR_OUTPUT_RNA="$2"
             shift 2
@@ -283,6 +298,10 @@ if [ -z "$VIASH_PAR_INPUT_META" ]; then
   ViashError '--input_meta' is a required argument. Use "--help" to get more information on the parameters.
   exit 1
 fi
+if [ -z "$VIASH_PAR_ORGANISM" ]; then
+  ViashError '--organism' is a required argument. Use "--help" to get more information on the parameters.
+  exit 1
+fi
 if [ -z "$VIASH_PAR_OUTPUT_RNA" ]; then
   ViashError '--output_rna' is a required argument. Use "--help" to get more information on the parameters.
   exit 1
@@ -320,6 +339,7 @@ par = {
   'id': $( if [ ! -z ${VIASH_PAR_ID+x} ]; then echo "'$VIASH_PAR_ID'"; else echo None; fi ),
   'input_count': $( if [ ! -z ${VIASH_PAR_INPUT_COUNT+x} ]; then echo "'$VIASH_PAR_INPUT_COUNT'"; else echo None; fi ),
   'input_meta': $( if [ ! -z ${VIASH_PAR_INPUT_META+x} ]; then echo "'$VIASH_PAR_INPUT_META'"; else echo None; fi ),
+  'organism': $( if [ ! -z ${VIASH_PAR_ORGANISM+x} ]; then echo "'$VIASH_PAR_ORGANISM'"; else echo None; fi ),
   'output_rna': $( if [ ! -z ${VIASH_PAR_OUTPUT_RNA+x} ]; then echo "'$VIASH_PAR_OUTPUT_RNA'"; else echo None; fi ),
   'output_mod2': $( if [ ! -z ${VIASH_PAR_OUTPUT_MOD2+x} ]; then echo "'$VIASH_PAR_OUTPUT_MOD2'"; else echo None; fi )
 }
@@ -403,7 +423,7 @@ adata.var['feature_types'] = "GEX"
 protein.var['feature_types'] = "ADT"
 
 # set uns 
-uns = { "dataset_id" : par["id"] }
+uns = { "dataset_id" : par["id"], "organism" : par["organism"] }
 adata.uns = uns
 protein.uns = uns
 
diff --git a/target/nextflow/common_datasets/download_azimuth_dataset/viash.yaml b/target/nextflow/common_datasets/download_azimuth_dataset/viash.yaml
--- a/target/nextflow/common_datasets/download_azimuth_dataset/viash.yaml
+++ b/target/nextflow/common_datasets/download_azimuth_dataset/viash.yaml
@@ -38,6 +38,15 @@ functionality:
     direction: "Input"
     multiple: false
     multiple_sep: ":"
+  - type: "string"
+    name: "--organism"
+    alternatives: []
+    description: "The organism of the dataset"
+    example: "human"
+    required: true
+    direction: "Input"
+    multiple: false
+    multiple_sep: ":"
   - type: "file"
     name: "--output_rna"
     alternatives: []
@@ -236,6 +245,13 @@ functionality:
         echo ""
       
       
+        echo "   --organism"
+        echo "        type: string, required parameter"
+        echo "        example: human"
+        echo "        The organism of the dataset"
+        echo ""
+      
+      
         echo "   --output_rna"
         echo "        type: file, required parameter, output"
         echo "        example: output_rna.h5ad"
@@ -304,6 +320,14 @@ functionality:
                   VIASH_PAR_INPUT_META=$(ViashRemoveFlags "$1")
                   shift 1
                   ;;
+              --organism)
+                  VIASH_PAR_ORGANISM="$2"
+                  shift 2
+                  ;;
+              --organism=*)
+                  VIASH_PAR_ORGANISM=$(ViashRemoveFlags "$1")
+                  shift 1
+                  ;;
               --output_rna)
                   VIASH_PAR_OUTPUT_RNA="$2"
                   shift 2
@@ -346,6 +370,10 @@ functionality:
         ViashError '--input_meta' is a required argument. Use "--help" to get more information on the parameters.
         exit 1
       fi
+      if [ -z "$VIASH_PAR_ORGANISM" ]; then
+        ViashError '--organism' is a required argument. Use "--help" to get more information on the parameters.
+        exit 1
+      fi
       if [ -z "$VIASH_PAR_OUTPUT_RNA" ]; then
         ViashError '--output_rna' is a required argument. Use "--help" to get more information on the parameters.
         exit 1
@@ -383,6 +411,7 @@ functionality:
         'id': $( if [ ! -z ${VIASH_PAR_ID+x} ]; then echo "'$VIASH_PAR_ID'"; else echo None; fi ),
         'input_count': $( if [ ! -z ${VIASH_PAR_INPUT_COUNT+x} ]; then echo "'$VIASH_PAR_INPUT_COUNT'"; else echo None; fi ),
         'input_meta': $( if [ ! -z ${VIASH_PAR_INPUT_META+x} ]; then echo "'$VIASH_PAR_INPUT_META'"; else echo None; fi ),
+        'organism': $( if [ ! -z ${VIASH_PAR_ORGANISM+x} ]; then echo "'$VIASH_PAR_ORGANISM'"; else echo None; fi ),
         'output_rna': $( if [ ! -z ${VIASH_PAR_OUTPUT_RNA+x} ]; then echo "'$VIASH_PAR_OUTPUT_RNA'"; else echo None; fi ),
         'output_mod2': $( if [ ! -z ${VIASH_PAR_OUTPUT_MOD2+x} ]; then echo "'$VIASH_PAR_OUTPUT_MOD2'"; else echo None; fi )
       }
@@ -466,7 +495,7 @@ functionality:
       protein.var['feature_types'] = "ADT"
       
       # set uns 
-      uns = { "dataset_id" : par["id"] }
+      uns = { "dataset_id" : par["id"], "organism" : par["organism"] }
       adata.uns = uns
       protein.uns = uns
       
@@ -496,6 +525,7 @@ functionality:
           download_azimuth_dataset__id = "viash_no_value"
           download_azimuth_dataset__input_count = "viash_no_value"
           download_azimuth_dataset__input_meta = "viash_no_value"
+          download_azimuth_dataset__organism = "viash_no_value"
           download_azimuth_dataset__output_rna = "viash_no_value"
           download_azimuth_dataset__output_mod2 = "viash_no_value"
           id = ""
@@ -548,6 +578,18 @@ functionality:
                 value = "${params.download_azimuth_dataset__input_meta}"
                 example = "https://www.ncbi.nlm.nih.gov/geo/download/?acc=GSE164378&format=file&file=GSE164378%5Fsc%2Emeta%2Edata%5F3P%2Ecsv%2Egz"
                 description = "Location URL to the GEO meta data file"
+              }
+              organism {
+                name = "organism"
+                otype = "--"
+                required = true
+                type = "string"
+                direction = "Input"
+                multiple = false
+                multiple_sep = ":"
+                value = "${params.download_azimuth_dataset__organism}"
+                example = "human"
+                description = "The organism of the dataset"
               }
               output_rna {
                 name = "output_rna"
@@ -952,5 +994,5 @@ info:
   output: "target/nextflow/common_datasets/download_azimuth_dataset"
   executable: "target/nextflow/common_datasets/download_azimuth_dataset/download_azimuth_dataset"
   viash_version: "0.5.1"
-  git_commit: "0ea195f52434e5eb89479a7be89b7d535bce4ad4"
+  git_commit: "53cafda52f02612563bed618cf8b7e232c59d4fa"
   git_remote: "https://github.com/openproblems-bio/neurips2021_multimodal_viash"
diff --git a/target/nextflow/common_datasets/download_totalvi_spleen_lymph/viash.yaml b/target/nextflow/common_datasets/download_totalvi_spleen_lymph/viash.yaml
--- a/target/nextflow/common_datasets/download_totalvi_spleen_lymph/viash.yaml
+++ b/target/nextflow/common_datasets/download_totalvi_spleen_lymph/viash.yaml
@@ -29,6 +29,15 @@ functionality:
     direction: "Input"
     multiple: false
     multiple_sep: ":"
+  - type: "string"
+    name: "--organism"
+    alternatives: []
+    description: "The organism of the dataset"
+    example: "mouse"
+    required: true
+    direction: "Input"
+    multiple: false
+    multiple_sep: ":"
   - type: "file"
     name: "--output_rna"
     alternatives: []
@@ -217,6 +226,13 @@ functionality:
         echo ""
       
       
+        echo "   --organism"
+        echo "        type: string, required parameter"
+        echo "        example: mouse"
+        echo "        The organism of the dataset"
+        echo ""
+      
+      
         echo "   --output_rna"
         echo "        type: file, required parameter, output"
         echo "        example: output_rna.h5ad"
@@ -277,6 +293,14 @@ functionality:
                   VIASH_PAR_INPUT=$(ViashRemoveFlags "$1")
                   shift 1
                   ;;
+              --organism)
+                  VIASH_PAR_ORGANISM="$2"
+                  shift 2
+                  ;;
+              --organism=*)
+                  VIASH_PAR_ORGANISM=$(ViashRemoveFlags "$1")
+                  shift 1
+                  ;;
               --output_rna)
                   VIASH_PAR_OUTPUT_RNA="$2"
                   shift 2
@@ -315,6 +339,10 @@ functionality:
         ViashError '--input' is a required argument. Use "--help" to get more information on the parameters.
         exit 1
       fi
+      if [ -z "$VIASH_PAR_ORGANISM" ]; then
+        ViashError '--organism' is a required argument. Use "--help" to get more information on the parameters.
+        exit 1
+      fi
       if [ -z "$VIASH_PAR_OUTPUT_RNA" ]; then
         ViashError '--output_rna' is a required argument. Use "--help" to get more information on the parameters.
         exit 1
@@ -347,6 +375,7 @@ functionality:
       par = {
         'id': $( if [ ! -z ${VIASH_PAR_ID+x} ]; then echo "'$VIASH_PAR_ID'"; else echo None; fi ),
         'input': $( if [ ! -z ${VIASH_PAR_INPUT+x} ]; then echo "'$VIASH_PAR_INPUT'"; else echo None; fi ),
+        'organism': $( if [ ! -z ${VIASH_PAR_ORGANISM+x} ]; then echo "'$VIASH_PAR_ORGANISM'"; else echo None; fi ),
         'output_rna': $( if [ ! -z ${VIASH_PAR_OUTPUT_RNA+x} ]; then echo "'$VIASH_PAR_OUTPUT_RNA'"; else echo None; fi ),
         'output_mod2': $( if [ ! -z ${VIASH_PAR_OUTPUT_MOD2+x} ]; then echo "'$VIASH_PAR_OUTPUT_MOD2'"; else echo None; fi )
       }
@@ -371,7 +400,7 @@ functionality:
       ###                     CREATE H5AD FOR BOTH MODALITIES                     ###
       ###############################################################################
       new_obs = adata.obs.rename(columns = {'cell_types': 'cell_type', 'batch_indices': 'batch'}, inplace = False)
-      uns = { "dataset_id" : par["id"] }
+      uns = { "dataset_id" : par["id"], "organism" : par["organism"] }
       
       print("Extracting RNA counts")
       adata_rna = anndata.AnnData(
@@ -421,6 +450,7 @@ functionality:
         params {
           download_totalvi_spleen_lymph__id = "viash_no_value"
           download_totalvi_spleen_lymph__input = "viash_no_value"
+          download_totalvi_spleen_lymph__organism = "viash_no_value"
           download_totalvi_spleen_lymph__output_rna = "viash_no_value"
           download_totalvi_spleen_lymph__output_mod2 = "viash_no_value"
           id = ""
@@ -461,6 +491,18 @@ functionality:
                 value = "${params.download_totalvi_spleen_lymph__input}"
                 example = "https://github.com/YosefLab/totalVI_reproducibility/raw/master/data/spleen_lymph_111.h5ad"
                 description = "Location URL to an h5ad file from the totalVI reproducibility github."
+              }
+              organism {
+                name = "organism"
+                otype = "--"
+                required = true
+                type = "string"
+                direction = "Input"
+                multiple = false
+                multiple_sep = ":"
+                value = "${params.download_totalvi_spleen_lymph__organism}"
+                example = "mouse"
+                description = "The organism of the dataset"
               }
               output_rna {
                 name = "output_rna"
@@ -862,5 +904,5 @@ info:
   output: "target/nextflow/common_datasets/download_totalvi_spleen_lymph"
   executable: "target/nextflow/common_datasets/download_totalvi_spleen_lymph/download_totalvi_spleen_lymph"
   viash_version: "0.5.1"
-  git_commit: "0ea195f52434e5eb89479a7be89b7d535bce4ad4"
+  git_commit: "53cafda52f02612563bed618cf8b7e232c59d4fa"
   git_remote: "https://github.com/openproblems-bio/neurips2021_multimodal_viash"
